"""WHAT THIS GUARDS — THE SOCKET ITSELF, which nothing in api/tests/ had ever touched.

Every other suite here exercises MODULES. test_liveness drives hardware -> rov ->
protocol and reads the JSON that would have gone on the wire; test_consumers boots the
real lifespan and calls route handlers directly. Both stop one layer short of the thing
the operator actually holds: a TCP connection to a uvicorn server, an HTTP upgrade, a
masked frame, a tether that gets yanked. Everything between `Telemetry.model_dump_json()`
and the bytes arriving at the handheld was unproven — including the four pieces of
api/main.py that exist for nothing else:

  * the `except Exception` around the receive loop, whose entire job is to keep one bad
    socket from taking the app down;
  * `parse_inbound()` returning None and the loop CONTINUING, so a frame the vehicle
    cannot understand costs a frame and not a connection;
  * `ws_unrouted`, added because a websocket upgrade to a typo'd path fell through to
    StaticFiles and answered HTTP 500 with an AssertionError in the log — and a 500 is
    what a BROKEN VEHICLE looks like to a client that retries on a schedule;
  * the watchdog in api/rov.py, which is the only thing standing between a tether that
    died at full throttle and a submarine that keeps going.

None of those can be reached by calling a function. They need a real server, a real
port, and a real client that misbehaves.

HOW THE SERVER IS STOOD UP. `uvicorn.Server` in a thread, over a socket this file bound
to PORT ZERO and then read the assigned port back off. Never a fixed port: a suite that
hardcodes 8000 fails on the one bench where the operator left the real server running,
which is the bench where the tests matter most, and two suites that both hardcode it
cannot run side by side at all. The listening socket is created here rather than by
uvicorn precisely so the port is known BEFORE anything starts serving on it.

What it serves is api/main.py, executed as shipped into an app object of this suite's
own — a FIRST boot, which is what `uvicorn main:app` gets in production and is not the
same operation as re-booting the `main.app` another suite has already used and shut
down. `_load_app_under_test` names the two shipped things that do not survive the
repeat, both of which turned out to be real defects and neither of which is a socket.

Shutdown is in `finally`, always, including the way out of a failed assertion. A test
process that leaves a server holding a port and a control loop turning is a test process
that poisons every run after it.

THE VEHICLE IS FORCED TO MockHardware FOR THIS SUITE, and that is a safety rule, not a
convenience. These checks ARM the vehicle and hold the throttle wide open to prove the
failsafe catches it. Run against `RealHardware` on the Pi that would spin both
propellers in a workshop with somebody's hands near them. The suite is about the
sockets; the hull underneath them is deliberately the simulated one, and it is restored
afterwards.

NO NEW DEPENDENCIES, INCLUDING FOR THE CLIENT. The websocket client below is a few
dozen lines of `socket` and `struct` against RFC 6455. That is not stubbornness: this
suite has to send things a library would refuse to send — a binary frame where the
server expects text, bytes that are not UTF-8, bytes that are not a frame at all — and a
well-behaved client library exists precisely to make those unreachable. It also has to
drop a connection the way a tether does, with a reset and no close handshake, and to
STOP READING while staying connected. Raw sockets are the only way to hold the wrong
end of the protocol on purpose.

stdlib unittest only, matching the rest of api/tests — see run.py for why there is no
framework here.
"""

from __future__ import annotations

import base64
import contextlib
import http.client
import importlib.util
import json
import logging
import os
import socket
import struct
import sys
import tempfile
import threading
import time
import traceback
import unittest
from pathlib import Path

# ---------------------------------------------------------------------------
# Isolation, BEFORE anything reads the environment
# ---------------------------------------------------------------------------
# This module boots the REAL app, and a real boot writes: a blackbox session journal,
# and — through NavService._recover_orphans — a rebuilt .geojson for any dive journal
# that never got a clean stop. Dive records are the one thing this project produces that
# cannot be regenerated by re-running anything, so a socket suite is not allowed
# anywhere near the real data/ directory.
#
# setdefault, not assignment: whichever test module in this run got here first has
# already pointed the settings at ITS temp tree and the settings objects are frozen
# dataclasses built at import time, so overwriting the variables now would change the
# environment without changing where anything is written — which is worse than either
# answer on its own. See the guard below, which checks the result rather than trusting
# the assignment.
_TMP = Path(tempfile.mkdtemp(prefix="neptune-network-"))
os.environ.setdefault("NAV_DATA_DIR", str(_TMP))
os.environ.setdefault("NAV_DIVES_DIR", str(_TMP / "dives"))
os.environ.setdefault("NAV_AREAS_DIR", str(_TMP / "areas"))
os.environ.setdefault("NAV_LUT_DIR", str(_TMP / "speed_luts"))
os.environ.setdefault("ROV_LOG_DIR", str(_TMP / "log"))
# The vehicle is simulated for this suite; see the module docstring for why that is a
# safety rule. Belt and braces with the settings override in setUpModule, because the
# settings object may already have been built by an earlier import.
os.environ.setdefault("NEPTUNE_HW", "mock")
# The whole Canal & River Trust network is not something to download while testing a
# socket. Same reasoning as the data dir: the flag is also forced in setUpModule,
# because by now it has probably already been read.
os.environ.setdefault("NAV_CRT_NATIONAL_AUTO", "0")
# The WOLFANG camera is genuinely not on this bench's network and the boot waits for its
# probe to time out. Shortening the wait changes how long the boot takes and nothing
# about what it finds.
os.environ.setdefault("WOLFANG_T_FAST", "0.25")
os.environ.setdefault("WOLFANG_T_SLOW", "0.25")

import uvicorn  # noqa: E402

from config import settings  # noqa: E402
from nav.config import settings as nav_settings  # noqa: E402
from protocol import COMMAND_NAMES  # noqa: E402


def _load_app_under_test():
    """Execute api/main.py into an app object of this suite's own, and return it.

    NOT `import main`, and the difference is the whole reason this function exists.
    `main.app` is a module-level singleton with module-level state hanging off it — one
    BlackBox, one ConnectionManager, one NavService, one camera control plane — and by
    the time this suite runs, another suite in the same process has usually already
    booted that app's lifespan and shut it down again. Booting it a SECOND time is not
    the same operation as booting it once, and two of the things it wakes up do not
    survive the repeat:

      * the lifespan CLOSES `app.state.bb` on the way out, and `ws_control` journals
        every new client before its own try-block — so the first socket this suite
        opened died on `I/O operation on closed file` and took the control loop with it;
      * `api/camera/cgi.py` cannot be restarted at all. `CgiClient.aclose()` cancels the
        queue worker and leaves `self._worker` pointing at the dead task, so the next
        `start()` sees a non-None worker and creates nothing — and `_enqueue` then puts
        a job on a queue nobody is reading and awaits its future with no timeout. The
        camera service's `refresh_menu()` on startup therefore never returns and the
        app never finishes coming up. It is INTERMITTENT, which is worse: `_enqueue`
        short-circuits while the circuit breaker is still open, so a second boot a few
        seconds after the first raises and carries on, and a second boot minutes later
        hangs forever. Measured both ways in one afternoon.

    Neither of those is a socket, and neither is this suite's to fix. api/main.py is
    executed here exactly as shipped — the same file, the same statements, in the same
    order — and what comes out is a first boot of a fresh app, which is precisely what
    `uvicorn main:app` gets in production. Nothing is stubbed and nothing is skipped.
    """
    path = Path(__file__).resolve().parent.parent / "main.py"
    spec = importlib.util.spec_from_file_location("neptune_main_under_test", path)
    if spec is None or spec.loader is None:  # pragma: no cover — main.py is right there
        raise ImportError(f"could not load the app under test from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# api/main.py runs `logging.basicConfig()` when it executes, and this module has to
# execute it at MODULE scope so that a bench missing fastapi/pydantic/uvicorn is reported
# by run.py as DEPS ("never loaded: needs X") rather than as a wall of failing checks.
# Those two facts collide: discovery imports every test_*.py, so merely HAVING this file
# would install a root handler and set the root level, and every other suite in the run
# would start printing INFO lines it has never printed before. The root logger is
# therefore put back exactly as it was found, and the vehicle's own logger is held quiet
# for the duration so the few records main.py emits on the way up do not land on a runner
# that did not ask for them.
_root = logging.getLogger()
_saved_root = (_root.handlers[:], _root.level)
_neptune_log = logging.getLogger("neptune")
_saved_neptune = _neptune_log.level
_neptune_log.setLevel(logging.ERROR)
try:
    neptune = _load_app_under_test()
finally:
    _neptune_log.setLevel(_saved_neptune)
    _root.handlers[:] = _saved_root[0]
    _root.setLevel(_saved_root[1])

# Belt and braces on the isolation above. nav.config caches its settings at import, and
# if any module in this process got there first the environment arrived too late — in
# which case this suite would write into the operator's real dive directory. A frozen
# dataclass is frozen against accident, not against a test that says why.
for _attr, _sub in (("data_dir", ""), ("dives_dir", "dives"), ("areas_dir", "areas"), ("speed_lut_dir", "speed_luts")):
    _want = _TMP / _sub if _sub else _TMP
    if not str(getattr(nav_settings, _attr)).startswith(tempfile.gettempdir()):
        object.__setattr__(nav_settings, _attr, _want)


# ---------------------------------------------------------------------------
# The knobs, named once
# ---------------------------------------------------------------------------
BIND_HOST = "127.0.0.1"  # loopback only — a test must not serve a network
CONTROL_PATH = "/ws/control"
# Paths this vehicle does NOT route a socket on. `/ws/nav` and `/ws/telemetry` are real
# and are deliberately absent from this list.
UNROUTED_PATHS = ("/ws/does-not-exist", "/ws/control/extra", "/ws", "/nope")

DEFAULT_TIMEOUT_S = 5.0  # ~75 telemetry periods at the shipped rate
SERVER_START_TIMEOUT_S = 45.0  # a cold boot brings up nav + the camera probe
SERVER_STOP_TIMEOUT_S = 30.0
CLIENT_SETTLE_S = 3.0  # how long the server may take to notice a drop
RECONNECT_CHURN = 4  # connect/serve/drop cycles, alternating the drop

# THE SLOW-CONSUMER WINDOW, AND WHY IT IS THIS LONG. Backpressure is not instant: before
# a stopped reader can push back on the server, the client's receive buffer, the
# server's send buffer and asyncio's own write buffer all have to fill, and telemetry is
# a small frame at a modest rate. Measured on the handheld (Windows 11, loopback), a
# client that stops reading takes on the order of ten seconds of held telemetry to reach
# the point where the server's next send blocks. The window is sized from that with
# margin. It is an upper bound on how long the CONDITION takes to arise, not on how long
# the property is checked — the property is checked continuously throughout.
#
# It is honest about what it cannot prove: on a machine with much larger socket buffers
# the window may end before the server is ever pushed back on, and then this class has
# observed a healthy loop under a condition it did not manage to create. The bytes the
# slow socket had queued are drained and reported for exactly that reason, so a green
# result can be read for what it is worth rather than taken on trust.
SLOW_HOLD_S = 15.0
SLOW_RCVBUF = 512  # ask the kernel for the smallest window it will give
SLOW_RESUME_S = 5.0  # after the slow reader drains, telemetry must return
# The largest silence a still-connected client may see on a still-running loop. Two
# seconds is ~30 telemetry periods at the shipped rate: far beyond scheduling jitter,
# far short of "the loop has stopped".
MAX_TELEMETRY_GAP_S = 2.0

WATCHDOG_SETTLE_S = 0.6  # loop periods of slack on top of watchdog_timeout_s

# Frame opcodes (RFC 6455 §5.2), spelled out because this file writes them by hand.
OP_TEXT, OP_BINARY, OP_CLOSE, OP_PING, OP_PONG = 0x1, 0x2, 0x8, 0x9, 0xA

# Bytes that are not text in any encoding: every byte value, which contains sequences no
# UTF-8 decoder will accept. Used both inside a frame and instead of one.
GARBAGE_BYTES = bytes(range(256))

# Valid JSON that is not an inbound message. Each of these parses cleanly and then fails
# the discriminated union in protocol.py, which is the case `parse_inbound` returns None
# for and the receive loop must simply skip.
JSON_THAT_IS_NOT_A_MESSAGE = (
    '{"hello": "world"}',
    '{"type": 17}',
    "[1, 2, 3]",
    '"a bare string"',
    "42",
    "null",
    "{}",
)

# Well-formed JSON objects carrying a `type` this vehicle does not serve.
UNKNOWN_MESSAGE_TYPES = (
    '{"type": "nonsense"}',
    '{"type": "control_v2", "throttle": 1.0}',
    '{"type": "telemetry", "armed": true}',  # an OUTBOUND name, sent inbound
)


# ---------------------------------------------------------------------------
# A websocket client made of nothing but a socket
# ---------------------------------------------------------------------------
class WsClosed(Exception):
    """The server ended this socket. `code` is the close code, or None for an EOF."""

    def __init__(self, code: int | None = None, reason: str = "") -> None:
        super().__init__(f"closed (code={code}) {reason}".strip())
        self.code = code
        self.reason = reason


class Ws:
    """One client connection, held at whatever end of the protocol a test needs.

    Deliberately NOT a well-behaved client. It will send a binary frame where the
    server expects text, bytes that are not UTF-8, and bytes that are not a frame; it
    will stop reading while staying connected; and it will drop the connection with a
    reset and no close handshake, which is what a tether coming out of a socket looks
    like on the wire. A library would make every one of those impossible, and every one
    of them is a thing api/main.py claims to survive.
    """

    def __init__(
        self, port: int, path: str = CONTROL_PATH, *, rcvbuf: int | None = None, timeout: float = DEFAULT_TIMEOUT_S
    ) -> None:
        self.port = port
        self.path = path
        self.timeout = timeout
        self._buf = b""
        self.rcvbuf = -1
        self.response = ""
        self.status_line = ""
        self.status = 0
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        if rcvbuf is not None:
            # Before connect, so the small window is what gets advertised in the SYN.
            # The kernel is free to clamp this upwards and usually does; what it gives
            # back is read and reported rather than assumed.
            with contextlib.suppress(OSError):
                self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, rcvbuf)
        self.sock.settimeout(timeout)
        try:
            self._handshake(port, path)
        except BaseException:
            # A connection that never came up must not survive as an open descriptor:
            # this suite opens a lot of sockets deliberately badly, and a leaked one
            # keeps the server counting a client that is not there.
            self.close()
            raise

    def _handshake(self, port: int, path: str) -> None:
        self.sock.connect((BIND_HOST, port))
        self.rcvbuf = self.sock.getsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF)
        key = base64.b64encode(os.urandom(16)).decode("ascii")
        self.sock.sendall(
            f"GET {path} HTTP/1.1\r\n"
            f"Host: {BIND_HOST}:{port}\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            f"Sec-WebSocket-Key: {key}\r\n"
            "Sec-WebSocket-Version: 13\r\n\r\n".encode("ascii")
        )
        head = b""
        while b"\r\n\r\n" not in head:
            chunk = self.sock.recv(4096)
            if not chunk:
                break
            head += chunk
        head, _, self._buf = head.partition(b"\r\n\r\n")
        self.response = head.decode("latin-1")
        self.status_line = self.response.splitlines()[0] if self.response else ""
        try:
            self.status = int(self.status_line.split(" ")[1])
        except (IndexError, ValueError):
            self.status = 0

    # ---- raw plumbing ----------------------------------------------------
    @staticmethod
    def _frame(opcode: int, payload: bytes) -> bytes:
        """One final, masked client frame. Clients MUST mask (RFC 6455 §5.3)."""
        n = len(payload)
        out = bytes([0x80 | opcode])
        if n < 126:
            out += bytes([0x80 | n])
        elif n <= 0xFFFF:
            out += bytes([0x80 | 126]) + struct.pack("!H", n)
        else:
            out += bytes([0x80 | 127]) + struct.pack("!Q", n)
        mask = os.urandom(4)
        return out + mask + bytes(b ^ mask[i % 4] for i, b in enumerate(payload))

    def send_frame(self, opcode: int, payload: bytes) -> None:
        self.sock.sendall(self._frame(opcode, payload))

    def send_raw(self, blob: bytes) -> None:
        """Bytes straight onto the connection, with no framing at all."""
        self.sock.sendall(blob)

    def send_text(self, text: str) -> None:
        self.send_frame(OP_TEXT, text.encode("utf-8"))

    def send_json(self, obj: dict) -> None:
        self.send_text(json.dumps(obj))

    def _fill(self, deadline: float) -> None:
        left = deadline - time.monotonic()
        if left <= 0:
            raise TimeoutError(f"nothing arrived on {self.path} before the deadline")
        self.sock.settimeout(left)
        chunk = self.sock.recv(65536)
        if not chunk:
            raise WsClosed(None, "the peer closed the stream without a close frame")
        self._buf += chunk

    def _need(self, n: int, deadline: float) -> None:
        while len(self._buf) < n:
            self._fill(deadline)

    def recv_frame(self, deadline: float) -> tuple[int, bytes]:
        self._need(2, deadline)
        opcode = self._buf[0] & 0x0F
        n = self._buf[1] & 0x7F
        off = 2
        if n == 126:
            self._need(4, deadline)
            n = struct.unpack("!H", self._buf[2:4])[0]
            off = 4
        elif n == 127:
            self._need(10, deadline)
            n = struct.unpack("!Q", self._buf[2:10])[0]
            off = 10
        self._need(off + n, deadline)
        payload = self._buf[off : off + n]
        self._buf = self._buf[off + n :]
        return opcode, payload

    def recv_json(self, timeout: float | None = None) -> dict:
        """The next application message, answering pings on the way past."""
        deadline = time.monotonic() + (self.timeout if timeout is None else timeout)
        while True:
            opcode, payload = self.recv_frame(deadline)
            if opcode == OP_PING:
                self.send_frame(OP_PONG, payload)
                continue
            if opcode == OP_PONG:
                continue
            if opcode == OP_CLOSE:
                code = struct.unpack("!H", payload[:2])[0] if len(payload) >= 2 else None
                raise WsClosed(code, payload[2:].decode("utf-8", "replace"))
            return json.loads(payload.decode("utf-8"))

    def next_of(self, kind: str, timeout: float | None = None) -> dict:
        """The next message of one `type`, skipping the rest of the stream."""
        deadline = time.monotonic() + (self.timeout if timeout is None else timeout)
        while True:
            left = deadline - time.monotonic()
            if left <= 0:
                raise TimeoutError(f"no {kind!r} message arrived on {self.path} in time")
            msg = self.recv_json(left)
            if msg.get("type") == kind:
                return msg

    def next_ack(self, c_id: str, timeout: float | None = None) -> dict:
        deadline = time.monotonic() + (self.timeout if timeout is None else timeout)
        while True:
            left = deadline - time.monotonic()
            if left <= 0:
                raise TimeoutError(f"no ack for c_id={c_id!r} arrived in time")
            msg = self.recv_json(left)
            if msg.get("type") == "ack" and msg.get("c_id") == c_id:
                return msg

    # ---- the three ways a client can go away ------------------------------
    def close_clean(self, code: int = 1000, timeout: float = DEFAULT_TIMEOUT_S) -> int | None:
        """The polite goodbye: a close frame, and the server's echo read back."""
        deadline = time.monotonic() + timeout
        echoed: int | None = None
        try:
            self.send_frame(OP_CLOSE, struct.pack("!H", code))
            while True:
                opcode, payload = self.recv_frame(deadline)
                if opcode == OP_CLOSE:
                    if len(payload) >= 2:
                        echoed = struct.unpack("!H", payload[:2])[0]
                    break
        except (OSError, TimeoutError, WsClosed):
            pass
        finally:
            self.close()
        return echoed

    def drop_abruptly(self) -> None:
        """What a tether does: a reset, no close frame, nothing said.

        SO_LINGER with a zero timeout makes close() send RST instead of FIN, so the
        server sees the connection destroyed rather than shut down — the same event a
        yanked Ethernet plug or a dead Pi produces, and a strictly harsher one than the
        FIN a plain close() would send.

        BOTH LAYOUTS OF `struct linger` ARE TRIED, because they genuinely differ: it is
        two ints on POSIX and two u_shorts in Winsock, and the wrong width is rejected
        with the option unset. Silently falling back to a plain close would still end
        the connection, but it would end it politely — this suite would then be checking
        the tidy case twice and the violent one never, on the platform this repo is
        developed on. If neither is accepted the close still happens; what is lost is
        only the harshness, and never the test.
        """
        for layout in ("ii", "hh"):
            try:
                self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_LINGER, struct.pack(layout, 1, 0))
                break
            except OSError:
                continue
        self.close()

    def drain(self, quiet_for: float = 1.0, limit: float = 20.0) -> int:
        """Read everything queued and say how much there was. Ends a slow-reader hold."""
        total = 0
        end = time.monotonic() + limit
        self.sock.settimeout(quiet_for)
        while time.monotonic() < end:
            try:
                chunk = self.sock.recv(1 << 16)
            except (TimeoutError, OSError):
                break
            if not chunk:
                break
            total += len(chunk)
        self.sock.settimeout(self.timeout)
        return total

    def close(self) -> None:
        with contextlib.suppress(OSError):
            self.sock.close()


# ---------------------------------------------------------------------------
# A real NEPTUNE server, on a real port nobody chose
# ---------------------------------------------------------------------------
class Server:
    """uvicorn on its own thread, bound to a port the OS chose.

    PORT ZERO, READ BACK. The listening socket is created and bound HERE, before uvicorn
    exists, which is the only arrangement in which the assigned port is known before
    anything starts serving on it. Nothing in this file may contain a port number: the
    bench that matters most is the one where the operator has left the real server
    running on 8000, and a suite that collides with it reports a broken vehicle.

    THE EVENT LOOP IS PINNED to stdlib asyncio. uvicorn's "auto" loop calls
    `uvloop.install()` where uvloop is present (the Pi), and that sets a PROCESS-WIDE
    event loop policy which every later `asyncio.run` in this test process would inherit
    — a socket suite quietly changing the loop other suites are measured on. The
    property under test is the app's, not the loop's.
    """

    def __init__(self) -> None:
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.bind((BIND_HOST, 0))
        self.port = self.sock.getsockname()[1]
        self._server = uvicorn.Server(
            uvicorn.Config(
                neptune.app,
                # Nothing printed by the server itself: this runner prints the report, and
                # log_config=None so a test does not reconfigure logging for the process.
                log_config=None,
                log_level="critical",
                access_log=False,
                lifespan="on",
                loop="asyncio",
            )
        )
        self._thread: threading.Thread | None = None

    def start(self) -> "Server":
        self._thread = threading.Thread(
            target=self._server.run, kwargs={"sockets": [self.sock]}, name="neptune-test-server", daemon=True
        )
        self._thread.start()
        deadline = time.monotonic() + SERVER_START_TIMEOUT_S
        while not self._server.started:
            if not self._thread.is_alive():
                raise RuntimeError("the server thread ended before the app came up")
            if time.monotonic() > deadline:
                # WHERE IT IS STUCK, NOT MERELY THAT IT IS. A boot that hangs is the one
                # failure in this file with no wire to inspect and no assertion message
                # to read, and "it did not come up" sends the next person to bisect the
                # suite order by hand — which is exactly what it cost the first time.
                # The server's own thread is the only place the answer can be.
                where = self._server_thread_stack()
                self.stop()
                raise RuntimeError(
                    f"the app did not come up within {SERVER_START_TIMEOUT_S:.0f}s; the "
                    f"server thread was here:\n{where}"
                )
            time.sleep(0.02)
        return self

    def _server_thread_stack(self) -> str:
        ident = self._thread.ident if self._thread is not None else None
        frame = sys._current_frames().get(ident) if ident is not None else None
        if frame is None:
            return "  (the server thread has no frame to report)"
        return "".join(traceback.format_stack(frame))

    def stop(self) -> bool:
        """Ask uvicorn to come down and wait for it. True if the thread actually ended."""
        self._server.should_exit = True
        alive = False
        if self._thread is not None:
            self._thread.join(SERVER_STOP_TIMEOUT_S)
            alive = self._thread.is_alive()
        with contextlib.suppress(OSError):
            self.sock.close()
        return not alive

    # ---- the HTTP plane, over the same real port -------------------------
    def http(self, path: str = "/healthz", timeout: float = DEFAULT_TIMEOUT_S) -> tuple[int, bytes]:
        conn = http.client.HTTPConnection(BIND_HOST, self.port, timeout=timeout)
        try:
            conn.request("GET", path)
            res = conn.getresponse()
            return res.status, res.read()
        finally:
            conn.close()

    def clients(self) -> int:
        status, body = self.http("/healthz")
        if status != 200:
            raise AssertionError(f"/healthz answered {status}, not 200")
        return int(json.loads(body)["clients"])

    def wait_for_clients(self, want: int, timeout: float = CLIENT_SETTLE_S) -> int:
        """Poll until the server agrees how many sockets it is holding."""
        deadline = time.monotonic() + timeout
        seen = -1
        while time.monotonic() < deadline:
            seen = self.clients()
            if seen == want:
                return seen
            time.sleep(0.05)
        return seen


# ONE SERVER, ONE BOOT, FOR THE WHOLE SUITE — AND IT HAS TO BE ONE.
#
# Not a style choice. The app under test has exactly one `app.state`, and its lifespan
# REPLACES hw / rov / manager / camera on the way up and CLOSES the blackbox on the way
# down, so a second server over the same app does not isolate anything, it corrupts what
# is already running: measured, on the first run of this file, a second server booted for
# one class swapped the ConnectionManager out from under the first server's control loop
# and then closed the blackbox that loop was still journalling to. And a second boot is
# not merely redundant, it can HANG — see the note in _load_app_under_test about the
# camera CGI client, which cannot be restarted. A suite that reports the vehicle broken
# because of its own fixture is worse than no suite.
#
# The good side of it: the later checks are served by the same process the malformed
# input was fired at, so an app that quietly died on a bad frame takes the rest of the
# suite with it instead of being replaced by a fresh instance that hides the corpse.
SERVER: Server | None = None
_SAVED: dict = {}


def setUpModule() -> None:
    global SERVER
    # The vehicle is forced to the simulation for the whole suite; see the module
    # docstring. Frozen dataclasses are frozen against accident, not against a test that
    # says why — and every one of these is put back in tearDownModule.
    _SAVED["hardware_backend"] = settings.hardware_backend
    object.__setattr__(settings, "hardware_backend", "mock")
    _SAVED["crt_national_auto"] = nav_settings.crt_national_auto
    object.__setattr__(nav_settings, "crt_national_auto", False)
    # Quiet, deliberately, and put back afterwards. Every check below drives the vehicle
    # into a state it is supposed to complain about — a socket dropped mid-throttle, a
    # frame it cannot parse, a re-arm refused over standing water — so without this the
    # suite prints a page of warnings that are the fixtures working correctly. A test
    # module that permanently silences the vehicle's logger would be a worse bug than
    # the noise, so the level is restored.
    _SAVED["log_levels"] = {
        name: logging.getLogger(name).level for name in ("neptune", "uvicorn.error", "uvicorn.access", "uvicorn.asgi")
    }
    for name in _SAVED["log_levels"]:
        logging.getLogger(name).setLevel(logging.CRITICAL)
    try:
        SERVER = Server().start()
    except BaseException:
        # unittest does not call tearDownModule when setUpModule raised, so everything
        # borrowed above is handed back here or it stays borrowed for the whole run —
        # a suite that could not start its own server must not also leave the next
        # suite's vehicle forced to the simulator and its logger switched off.
        _restore_globals()
        raise


def _restore_globals() -> None:
    for name, level in _SAVED.pop("log_levels", {}).items():
        logging.getLogger(name).setLevel(level)
    if "hardware_backend" in _SAVED:
        object.__setattr__(settings, "hardware_backend", _SAVED.pop("hardware_backend"))
    if "crt_national_auto" in _SAVED:
        object.__setattr__(nav_settings, "crt_national_auto", _SAVED.pop("crt_national_auto"))


def tearDownModule() -> None:
    global SERVER
    stopped = True
    try:
        if SERVER is not None:
            stopped = SERVER.stop()
    finally:
        SERVER = None
        _restore_globals()
    # SAID OUT LOUD, not swallowed. A test process that walks away from a thread still
    # serving a port is a test process that poisons whatever runs next, and "the suite
    # finished" is not the same claim as "the server it started is gone".
    if not stopped:
        raise RuntimeError(
            f"the test server was asked to stop and was still running " f"{SERVER_STOP_TIMEOUT_S:.0f}s later"
        )


def quiesce() -> None:
    """Put the vehicle back where every check expects to find it: disarmed and dry.

    These checks share one server and therefore one RovState, so a check that leaves the
    thrusters armed hands the next one a vehicle it did not set up. Done through the
    state object rather than over a socket because this is fixture work, not a
    measurement — the measurements all go over the wire.
    """
    rov = getattr(neptune.app.state, "rov", None)
    if rov is None:
        return
    hw = neptune.app.state.hw
    if hasattr(hw, "_set_leak"):
        hw._set_leak("NORMAL")
    rov._set_armed(False)
    rov._failsafe = False


class SocketCase(unittest.TestCase):
    """Base: every socket a check opens is closed again, pass or fail."""

    @property
    def server(self) -> Server:
        srv = SERVER
        assert srv is not None, "the server fixture never came up"
        return srv

    def setUp(self) -> None:
        self._open: list[Ws] = []
        quiesce()

    def tearDown(self) -> None:
        for ws in self._open:
            with contextlib.suppress(Exception):
                ws.close()
        quiesce()

    def ws(self, path: str = CONTROL_PATH, **kw) -> Ws:
        client = Ws(self.server.port, path, **kw)
        self._open.append(client)
        return client

    def assert_app_is_still_serving(self, why: str) -> None:
        """The whole point of the malformed-input checks: the APP, not the socket.

        Two independent witnesses, because they fail for different reasons: the HTTP
        plane answering proves the process and the event loop are alive, and a NEW
        control socket being served telemetry proves the control loop is still turning
        and still accepting clients. An app can pass the first and fail the second.
        """
        status, _ = self.server.http("/healthz")
        self.assertEqual(200, status, f"/healthz stopped answering after {why}")
        fresh = self.ws()
        frame = fresh.next_of("telemetry")
        self.assertEqual("telemetry", frame["type"])
        fresh.close_clean()


# ---------------------------------------------------------------------------
class ControlSocketTest(SocketCase):
    """Connect, be served, go away — including going away badly, over and over.

    THE SEQUENCE NUMBER IS THE POINT OF THE RECONNECT CHECKS. `seq` is what the client's
    gap detector counts on (protocol.py: "monotonically increasing frame number") and
    main.py only advances it while somebody is attached, precisely so a tether dropout
    does not open a hole the client would report as packet loss. Both halves of that are
    checked here: it never goes backwards across a reconnect, and it never skips while
    one client is continuously attached.
    """

    def test_a_a_client_that_connects_is_served_telemetry(self):
        client = self.ws()
        first = client.next_of("telemetry")
        self.assertEqual("telemetry", first["type"])
        # The frame is the shipped contract, not a stub: fields the console cannot
        # render without must be present, and `leak_state` must never be missing —
        # a bool-only client reading an absent stage is the failure protocol.py's
        # UNKNOWN stage exists to prevent.
        for field in ("armed", "left", "right", "leak", "leak_state", "mock", "seq"):
            self.assertIn(field, first, f"the wire frame has no {field!r}")
        self.assertTrue(first["mock"], "this suite must never run against a real hull")

    def test_b_sequence_numbers_do_not_skip_for_an_attached_client(self):
        client = self.ws()
        seqs = [client.next_of("telemetry")["seq"] for _ in range(6)]
        self.assertTrue(all(isinstance(s, int) for s in seqs), seqs)
        self.assertEqual(
            [seqs[0] + i for i in range(len(seqs))],
            seqs,
            "a client that never left was given a gap in the sequence, "
            "which its own gap detector will report as lost packets",
        )

    def test_c_a_clean_close_is_answered_and_the_server_lets_go(self):
        client = self.ws()
        client.next_of("telemetry")
        code = client.close_clean(1000)
        self.assertIn(code, (1000, None), f"the server answered a clean close with {code}")
        self.assertEqual(0, self.server.wait_for_clients(0), "the server is still counting a client that said goodbye")

    def test_d_an_abrupt_drop_is_noticed_and_let_go_of(self):
        client = self.ws()
        client.next_of("telemetry")
        self.assertEqual(1, self.server.wait_for_clients(1))
        client.drop_abruptly()
        self.assertEqual(
            0,
            self.server.wait_for_clients(0),
            "a socket that was reset is still being counted and broadcast "
            "to; a client list that only shrinks on a polite goodbye grows "
            "for the whole of a flaky dive",
        )

    def test_e_telemetry_resumes_and_seq_stays_monotonic_across_reconnect_churn(self):
        """Connect, be served, drop — alternating polite and violent — and again.

        The alternation matters: a clean close and a reset arrive at the server as
        different events (WebSocketDisconnect versus a connection destroyed under it),
        and a vehicle that survives one and not the other survives a tidy laboratory
        and not a canal.
        """
        highest = 0
        for cycle in range(RECONNECT_CHURN):
            client = Ws(self.server.port)
            try:
                seen = [client.next_of("telemetry")["seq"] for _ in range(3)]
                self.assertGreater(
                    seen[0],
                    highest,
                    f"cycle {cycle}: telemetry came back numbered {seen[0]}, at or below "
                    f"the {highest} the last connection had already been shown — a "
                    "sequence that repeats is a gap detector that cannot work",
                )
                self.assertEqual([seen[0] + i for i in range(len(seen))], seen, f"cycle {cycle}: {seen}")
                highest = seen[-1]
            finally:
                if cycle % 2:
                    client.drop_abruptly()
                else:
                    client.close_clean()
            self.server.wait_for_clients(0)


# ---------------------------------------------------------------------------
class MalformedInputTest(SocketCase):
    """Nothing a client can send may take the vehicle down.

    api/main.py has explicit handling for every case below — `parse_inbound` returning
    None, the broad `except Exception` around the receive loop, and `ws_unrouted` — and
    none of it had ever been executed by a test. Handling that is never exercised is
    handling that is believed rather than known, and the failure mode is not subtle: a
    console with a stale URL retries on a schedule, so one wrong path spends the whole
    dive filling the Pi's log with fake internal errors and hiding the real ones.

    The distinction each check draws is between the SOCKET and the APP. Some of these
    inputs legitimately cost the offending connection — a frame the websocket layer
    cannot decode ends that conversation, and should. None of them may cost the vehicle.
    """

    def test_a_a_binary_frame_where_text_was_expected_does_not_take_the_app_down(self):
        client = self.ws()
        client.next_of("telemetry")
        client.send_frame(OP_BINARY, GARBAGE_BYTES)
        # The socket may or may not survive this one — the server asks for text and this
        # is not text. What is not negotiable is the app.
        with contextlib.suppress(Exception):
            client.recv_json(1.0)
        self.assert_app_is_still_serving("a binary frame of arbitrary bytes")

    def test_b_bytes_that_are_not_utf8_do_not_take_the_app_down(self):
        client = self.ws()
        client.next_of("telemetry")
        client.send_frame(OP_TEXT, GARBAGE_BYTES)  # a TEXT frame that is not text
        with contextlib.suppress(Exception):
            client.recv_json(1.0)
        self.assert_app_is_still_serving("a text frame carrying invalid UTF-8")

    def test_c_bytes_that_are_not_a_frame_at_all_do_not_take_the_app_down(self):
        client = self.ws()
        client.next_of("telemetry")
        client.send_raw(GARBAGE_BYTES * 4)  # no framing whatsoever
        with contextlib.suppress(Exception):
            client.recv_json(1.0)
        self.assert_app_is_still_serving("raw bytes that are not a websocket frame")

    def test_d_valid_json_that_is_not_a_message_costs_a_frame_not_the_connection(self):
        """This is the one where the SOCKET must survive too.

        `parse_inbound` answers None for anything that does not match the inbound union
        and main.py `continue`s, which is the whole difference between a console that
        drops a frame and a console that has to reconnect. A client sending a shape the
        vehicle has not heard of is a client running older or newer code, and the answer
        to that is to ignore the frame, not to hang up on the operator.
        """
        client = self.ws()
        before = client.next_of("telemetry")["seq"]
        for blob in JSON_THAT_IS_NOT_A_MESSAGE:
            client.send_text(blob)
        after = client.next_of("telemetry")
        self.assertGreater(
            after["seq"], before, "the socket stopped being served after JSON the vehicle " "could not interpret"
        )
        self.assert_app_is_still_serving("valid JSON that is not an inbound message")

    def test_e_an_unknown_message_type_costs_a_frame_not_the_connection(self):
        client = self.ws()
        before = client.next_of("telemetry")["seq"]
        for blob in UNKNOWN_MESSAGE_TYPES:
            client.send_text(blob)
        after = client.next_of("telemetry")
        self.assertGreater(after["seq"], before, "an unknown message type ended the connection")
        self.assert_app_is_still_serving("an unknown message type")

    def test_f_an_unknown_command_name_is_refused_with_a_reason(self):
        """A command the vehicle does not have is ANSWERED, not dropped.

        The §3 lifecycle is recv -> validate -> apply -> ack, and validate failing is
        still an ack: a console that sent a command and heard nothing cannot tell a
        refusal from a dead tether, and the two need opposite responses from an
        operator.
        """
        name = "do_the_impossible"
        self.assertNotIn(name, COMMAND_NAMES, "pick a name the vehicle really lacks")
        client = self.ws()
        client.next_of("telemetry")
        client.send_json({"type": "command", "name": name, "c_id": "unknown-1"})
        ack = client.next_ack("unknown-1")
        self.assertFalse(ack["ok"], ack)
        self.assertTrue(ack.get("reason"), "a refusal with no reason is a button that " "silently does nothing")
        self.assertEqual(name, ack["name"])

    def test_g_a_websocket_upgrade_to_an_unrouted_path_is_refused_not_crashed(self):
        """A 500 is what a BROKEN VEHICLE looks like. A typo is not a broken vehicle.

        Before `ws_unrouted` existed the upgrade fell through to StaticFiles, whose
        first line asserts the scope is http, and the handshake was answered with HTTP
        500 and a traceback. The client retries on a schedule, so that is not one bad
        line in a log — it is the whole dive's worth of them, on top of the real ones.
        """
        for path in UNROUTED_PATHS:
            with self.subTest(path=path):
                client = self.ws(path)
                self.assertNotEqual(
                    101,
                    client.status,
                    f"{path} accepted a websocket upgrade; this vehicle "
                    "serves /ws/control, /ws/nav and /ws/telemetry",
                )
                self.assertLess(
                    client.status,
                    500,
                    f"{path} answered {client.status_line!r} — a 5xx is the "
                    "vehicle reporting itself broken over a client's typo",
                )
                self.assertGreaterEqual(
                    client.status, 400, f"{path} answered {client.status_line!r}, which " "is not a refusal"
                )
        self.assert_app_is_still_serving("websocket upgrades to unrouted paths")


# ---------------------------------------------------------------------------
class FailsafeWatchdogTest(SocketCase):
    """A dead socket must stop the propellers, and it must say so honestly.

    The watchdog in api/rov.py is the only thing between a tether that failed at full
    throttle and a submarine that keeps going, and until this file existed it had never
    been tripped by an actual socket dying — only by advancing a clock in a unit test.
    The two are not the same claim: the watchdog runs on the control loop, and the
    control loop is exactly what a dying socket is capable of disturbing.
    """

    def _drive(self, client: Ws) -> dict:
        client.next_of("telemetry")
        client.send_json({"type": "command", "name": "arm", "c_id": "arm-1"})
        ack = client.next_ack("arm-1")
        self.assertTrue(ack["ok"], f"the vehicle refused to arm: {ack}")
        deadline = time.monotonic() + DEFAULT_TIMEOUT_S
        while time.monotonic() < deadline:
            client.send_json({"type": "control", "throttle": 1.0, "steer": 0.0})
            frame = client.next_of("telemetry")
            if frame["left"] > 0.5 and frame["right"] > 0.5:
                return frame
        raise AssertionError("the vehicle never reported the thrusters running")

    def test_a_a_dead_socket_zeroes_the_thrusters(self):
        client = self.ws()
        driving = self._drive(client)
        self.assertTrue(driving["armed"])
        client.drop_abruptly()
        time.sleep(settings.watchdog_timeout_s + WATCHDOG_SETTLE_S)

        rov = neptune.app.state.rov
        self.assertTrue(rov._failsafe, "the control frames stopped and the failsafe never latched")
        # The reading the operator would see, over a NEW real socket — the failsafe is
        # only worth anything if it reaches the wire.
        back = self.ws()
        frame = back.next_of("telemetry")
        self.assertEqual(
            (0.0, 0.0),
            (frame["left"], frame["right"]),
            "the tether died at full throttle and the vehicle is still " f"driving: {frame['left']} / {frame['right']}",
        )
        # ARMED STAYS TRUE ON PURPOSE. The watchdog zeroes the thrusters; it does not
        # quietly disarm, because "the vehicle is armed and the failsafe is holding it"
        # and "the vehicle is disarmed" are different states and the operator who
        # reconnects has to be told which one they have.
        self.assertTrue(
            frame["armed"],
            "the failsafe disarmed the vehicle instead of zeroing it; the "
            "operator who reconnects cannot tell what state they are in",
        )

    def test_b_control_resuming_clears_the_failsafe(self):
        """Recovery is half the contract, and the half that gets skipped.

        A failsafe that latches and never lets go is its own fault: the tether flaps for
        a second, and the sub is dead in the water until somebody restarts the service.
        """
        client = self.ws()
        self._drive(client)
        client.drop_abruptly()
        time.sleep(settings.watchdog_timeout_s + WATCHDOG_SETTLE_S)
        self.assertTrue(neptune.app.state.rov._failsafe)

        back = self.ws()
        back.next_of("telemetry")
        deadline = time.monotonic() + DEFAULT_TIMEOUT_S
        while time.monotonic() < deadline:
            back.send_json({"type": "control", "throttle": 1.0, "steer": 0.0})
            frame = back.next_of("telemetry")
            if frame["left"] > 0.5:
                self.assertFalse(neptune.app.state.rov._failsafe)
                return
        self.fail("the vehicle never came back after the failsafe, on a reconnected " "socket sending control frames")


# ---------------------------------------------------------------------------
class LeakResetTest(SocketCase):
    """`leak_reset` end to end: the one command the vehicle is allowed to REFUSE.

    Everything else in COMMAND_NAMES simply happens. This one dismisses the vehicle's
    strongest claim about itself, so it goes through the full recv -> validate -> apply
    -> ack lifecycle over a real socket, and the ack has to carry the refusal AND the
    reason. A button that silently does nothing when it is refused teaches an operator
    that the button is broken, and the next thing they stop believing is the console.
    """

    def setUp(self):
        super().setUp()
        hw = neptune.app.state.hw
        if not hasattr(hw, "_set_leak"):
            self.skipTest(
                "this vehicle's hardware backend has no bench hook for wetting "
                "a probe, so the refusal-while-wet rule cannot be reached here"
            )
        self.hw = hw

    def _leak_reset(self, client: Ws, c_id: str) -> dict:
        client.send_json({"type": "command", "name": "leak_reset", "c_id": c_id})
        return client.next_ack(c_id)

    def _wait_for_stage(self, client: Ws, stage: str) -> dict:
        deadline = time.monotonic() + DEFAULT_TIMEOUT_S
        frame = {}
        while time.monotonic() < deadline:
            frame = client.next_of("telemetry")
            if frame["leak_state"] == stage:
                return frame
        raise AssertionError(f"the hull never reported {stage} " f"(last: {frame.get('leak_state')!r})")

    def test_a_a_re_arm_on_a_dry_hull_is_acked_ok_and_counted(self):
        client = self.ws()
        before = self._wait_for_stage(client, "NORMAL")
        ack = self._leak_reset(client, "dry-1")
        self.assertTrue(ack["ok"], ack)
        self.assertIsNone(ack["reason"], "an accepted command carries no refusal reason")
        after = self._wait_for_stage(client, "NORMAL")
        self.assertEqual(
            before["leak_rearms"] + 1,
            after["leak_rearms"],
            "the re-arm was acked ok and the vehicle did not count it; "
            "leak_rearms is on the wire so the console can say whether the "
            "NORMAL it is showing was restored by hand or never in doubt",
        )

    def test_b_a_re_arm_is_refused_while_a_probe_is_wet_and_the_ack_says_why(self):
        client = self.ws()
        self._wait_for_stage(client, "NORMAL")
        self.hw._set_leak("WARN")
        wet = self._wait_for_stage(client, "WARN")

        ack = self._leak_reset(client, "wet-1")
        self.assertFalse(
            ack["ok"],
            "the vehicle acked ok=true for a re-arm it was standing in "
            "water for; the console now believes the detector is armed",
        )
        reason = ack.get("reason") or ""
        self.assertTrue(reason, "the refusal reached the console with no reason at all")
        self.assertIn("wet", reason.lower(), f"the ack refused without saying that water is the cause: {reason!r}")

        after = self._wait_for_stage(client, "WARN")
        self.assertEqual(wet["leak_rearms"], after["leak_rearms"], "a refused re-arm was counted as one anyway")
        self.assertEqual("WARN", after["leak_state"], "the refused re-arm cleared the stage regardless")
        self.assertTrue(after["leak"], "the single-bit alarm went quiet while a probe was still wet")

    def test_c_the_hull_dries_and_the_re_arm_is_accepted_again(self):
        client = self.ws()
        self.hw._set_leak("WARN")
        self._wait_for_stage(client, "WARN")
        self.assertFalse(self._leak_reset(client, "wet-2")["ok"])
        self.hw._set_leak("NORMAL")
        self._wait_for_stage(client, "NORMAL")
        ack = self._leak_reset(client, "dry-2")
        self.assertTrue(ack["ok"], f"the hull dried and the re-arm is still refused: {ack}")


# ---------------------------------------------------------------------------
class SlowConsumerTest(SocketCase):
    """ONE CLIENT THAT STOPS READING MUST NOT STOP THE VEHICLE.

    The control loop in api/main.py does the whole of the vehicle's real-time work in one
    task: it advances the simulation, RUNS THE WATCHDOG, journals the blackbox, and only
    then broadcasts. Broadcasting is `await ws.send_text(...)` per client, in a loop, and
    an awaited send does not return until the transport is willing to take the bytes. So
    a client that stops draining its socket is, mechanically, a client that can hold the
    watchdog still — and a watchdog that is held still is a failsafe that has been
    switched off by a stranger with a laptop.

    THE EXPERIMENT RUNS ONCE, IN setUpClass, and the checks below read what it recorded.
    Four different facts come out of one held condition, and running it four times would
    be four chances for the condition to arise differently; separating the ASSERTIONS is
    what makes the report legible, not separating the experiment.

    THIS CLASS IS NAMED SO THAT IT SORTS LAST. unittest runs a module's classes in name
    order, and this is the one class here that deliberately drives the app into a state
    it may not come out of. It cannot be given a server of its own — see the note on
    SERVER above, one `main.app` cannot host two lifespans — so instead it goes at the
    end, where a control loop that stayed wedged costs nothing but its own report. It
    still drains the stalled socket and checks the vehicle came back (see the last
    check), because leaving the app poisoned would be a finding of its own.

    WHAT A GREEN RESULT HERE IS WORTH. Backpressure has to be created before it can be
    survived, and creating it means filling the client's receive buffer, the server's
    send buffer and asyncio's write buffer with telemetry, which takes seconds and takes
    a different number of them on every kernel. If the window ends before the server was
    ever pushed back on, these checks watched a healthy loop under a condition that never
    arrived. `queued_bytes` — how much the stalled socket had waiting when it finally
    read — is recorded and printed in the failure messages so the reader can tell those
    two situations apart instead of taking the green on trust.
    """

    # what the experiment recorded
    gaps: list[float] = []
    frames: int = 0
    http_probes: list[tuple[int, float]] = []
    queued_bytes: int = -1
    resumed_seq: int | None = None
    resume_error: str | None = None
    failsafe_after_stall: bool | None = None
    drove_before_stall: tuple[float, float] = (-1.0, -1.0)
    thrust_after_stall: tuple[float, float] = (-1.0, -1.0)
    rcvbuf: int = -1

    @classmethod
    def setUpClass(cls):
        cls._run_experiment()

    @classmethod
    def tearDownClass(cls):
        quiesce()

    @classmethod
    def _run_experiment(cls):
        srv = SERVER
        assert srv is not None, "the server fixture never came up"
        healthy = Ws(srv.port, timeout=MAX_TELEMETRY_GAP_S)
        slow = Ws(srv.port, rcvbuf=SLOW_RCVBUF, timeout=1.0)
        cls.rcvbuf = slow.rcvbuf
        # The HTTP plane is sampled from ANOTHER THREAD, on its own connections, and
        # deliberately not from the read loop below: a blocking health request taken in
        # between two frame reads would show up as a gap in telemetry that this suite
        # caused itself, and the whole finding here is the size of those gaps. Two
        # observers, two threads, one condition.
        probes: list[tuple[int, float]] = []
        stop_probing = threading.Event()

        def _poll_health():
            while not stop_probing.wait(1.0):
                t0 = time.monotonic()
                try:
                    status, _ = srv.http("/healthz", timeout=MAX_TELEMETRY_GAP_S)
                except Exception:  # noqa: BLE001 — a failure to answer IS the reading
                    status = 0
                probes.append((status, time.monotonic() - t0))

        poller = threading.Thread(target=_poll_health, name="neptune-test-health", daemon=True)
        try:
            healthy.next_of("telemetry", timeout=DEFAULT_TIMEOUT_S)
            # ---- hold the condition, and watch the loop through the good socket ----
            poller.start()
            gaps: list[float] = []
            started = last = time.monotonic()
            frames = 0
            while time.monotonic() - started < SLOW_HOLD_S:
                try:
                    msg = healthy.recv_json()
                except (TimeoutError, OSError, WsClosed):
                    continue
                if msg.get("type") != "telemetry":
                    continue
                now = time.monotonic()
                gaps.append(now - last)
                last = now
                frames += 1
            gaps.append(time.monotonic() - last)  # the silence the window ended in
            stop_probing.set()
            poller.join(timeout=CLIENT_SETTLE_S)
            cls.gaps, cls.frames, cls.http_probes = gaps, frames, list(probes)

            # ---- while it is still held: is the failsafe still running? ----
            # The receive side of a socket is not the send side, so commands still land
            # even when nothing can be broadcast: this drives the thrusters through the
            # ws handler task and then goes quiet. If the control loop is turning, the
            # watchdog zeroes them. If it is not, a client that stopped reading has
            # switched the failsafe off.
            rov = neptune.app.state.rov
            healthy.send_json({"type": "command", "name": "arm", "c_id": "slow-arm"})
            deadline = time.monotonic() + 2.0
            while time.monotonic() < deadline and not (rov.left > 0.5 and rov.right > 0.5):
                healthy.send_json({"type": "control", "throttle": 1.0, "steer": 0.0})
                time.sleep(0.05)
            # RECORDED BEFORE THE SILENCE, because the check below is worthless without
            # it: a watchdog that did not latch on a vehicle that was never driving is
            # a watchdog behaving perfectly, and reporting that as the failsafe being
            # disabled would be this suite crying wolf about its own setup.
            cls.drove_before_stall = (rov.left, rov.right)
            time.sleep(settings.watchdog_timeout_s + WATCHDOG_SETTLE_S)
            cls.failsafe_after_stall = bool(rov._failsafe)
            cls.thrust_after_stall = (rov.left, rov.right)
            quiesce()

            # ---- end the condition, and see whether the vehicle comes back ----
            cls.queued_bytes = slow.drain()
            try:
                cls.resumed_seq = healthy.next_of("telemetry", timeout=SLOW_RESUME_S)["seq"]
            except Exception as exc:  # noqa: BLE001 — recorded, asserted on below
                cls.resume_error = f"{type(exc).__name__}: {exc}"
        finally:
            stop_probing.set()
            slow.close()
            healthy.close()

    def _evidence(self) -> str:
        return (
            f"(held {SLOW_HOLD_S:.0f}s; telemetry frames reaching the healthy client: "
            f"{self.frames}; the stalled socket had {self.queued_bytes} bytes waiting "
            f"when it finally read, with SO_RCVBUF={self.rcvbuf})"
        )

    def test_a_telemetry_kept_reaching_a_client_that_was_reading(self):
        self.assertTrue(self.gaps, "the experiment recorded nothing at all")
        worst = max(self.gaps)
        self.assertLessEqual(
            worst,
            MAX_TELEMETRY_GAP_S,
            f"a client that stopped reading stalled the control loop for {worst:.1f}s. "
            "Everything on that loop stops together — telemetry to every OTHER client, "
            "the blackbox, and the thruster watchdog — so this is not a rendering "
            f"problem, it is one stranger's socket holding the failsafe still. "
            f"{self._evidence()}",
        )

    def test_b_the_http_plane_kept_answering(self):
        """Which half stopped? This is how the report says so.

        If HTTP kept answering while telemetry stalled, the event loop is fine and the
        CONTROL LOOP is what was blocked — a precise finding. If HTTP stalled too, the
        whole process was held, which is a different and worse one.
        """
        self.assertTrue(self.http_probes, "no health probes were taken")
        bad = [p for p in self.http_probes if p[0] != 200]
        self.assertEqual(
            [],
            bad,
            f"/healthz stopped answering 200 while one client was not "
            f"reading: {self.http_probes} {self._evidence()}",
        )

    def test_c_the_failsafe_still_ran_while_a_client_was_not_reading(self):
        self.assertIsNotNone(self.failsafe_after_stall, "the experiment never reached the failsafe check")
        # The premise, checked first: a watchdog that did not fire on a vehicle that was
        # never driving is a watchdog working correctly, and the finding below would be
        # this suite misreading its own setup.
        self.assertGreater(
            min(self.drove_before_stall),
            0.5,
            "the thrusters were never driving, so there was nothing for "
            f"the failsafe to catch: {self.drove_before_stall}",
        )
        self.assertTrue(
            self.failsafe_after_stall,
            "the thrusters were driven and the control frames then stopped, and the "
            f"watchdog never latched — thrusters left at {self.thrust_after_stall}. A "
            "client that simply stops reading its socket therefore disables the one "
            f"mechanism that stops a runaway vehicle. {self._evidence()}",
        )

    def test_d_the_vehicle_comes_back_when_the_slow_client_drains(self):
        """Whatever the answer above, the app must not be permanently poisoned."""
        self.assertIsNone(
            self.resume_error,
            f"telemetry never returned after the stalled client drained "
            f"{self.queued_bytes} bytes: {self.resume_error}",
        )
        self.assertIsNotNone(self.resumed_seq)


if __name__ == "__main__":
    unittest.main()
