"""WHAT THIS GUARDS — the CONSUMERS of a null, which is where every regression lands.

THE INDICTMENT THIS SUITE EXISTS TO ANSWER. Three review rounds running, the vehicle
side was made honest and the whole api suite went green — while the code that READS
those fields crashed, coerced, or quietly disagreed with itself. Making a field
Optional is a change to every file that touches it, and the files that touch it are
never the files anyone is editing. So: the vehicle side is checked by
tests/test_liveness.py (hardware readback -> the JSON on the wire); this checks what
happens to the null AFTERWARDS.

WHAT "AFTERWARDS" TURNED OUT TO MEAN, in the round that produced these tests:

  * POST /api/origin did `round(svc.last_sample.heading_deg, 1)` with no guard, so
    capturing a launch point on a hull whose BNO085 had stopped answering raised a
    TypeError inside the handler — a 500 on the one call that has to succeed before a
    dive can be logged at all. And the field it was writing into could not hold the
    answer anyway: heading0 0.0 is DUE NORTH, which is a bearing, not an admission.
  * nav/calibrate.py read the dive log with `s.get("heading_deg", 0.0)`. A default
    only fires on a MISSING key, and divelog.py writes a dead chip as the key PRESENT
    AND NULL — so the default never fired, the None went into _unwrap's subtraction,
    and `nav.cli calibrate` died on every log from a dive where a sensor stopped. That
    present-versus-absent distinction is the single sharpest edge in this file.
  * /ws/nav and /ws/control described the same vehicle differently in the same tick:
    telemetry said gyro_only=null (navigation cannot say) while the nav frame beside
    it said gyro_only=false (navigation looked, and it is fine). One console reads
    both sockets.
  * a completely healthy boot logged "navigation has STOPPED answering for this hull"
    at WARNING, because the control loop's first tick beat nav_svc.start() to it. A
    warning that fires on every healthy start is a warning nobody reads, and the day
    it means something it will look exactly like the day it did not.
  * and the contract itself: a field that is Optional in protocol.py is only Optional
    if a null actually survives model_validate_json in both directions, with the key
    still ON the wire — a consumer that asks `if "depth" in frame` must not be shown a
    dead sensor as a missing field.

WHY THIS BORROWS test_liveness.Chain RATHER THAN BUILDING ITS OWN VEHICLE. The
consumer side has to be tested against THE SAME chain the producer side is certified
on — one MockHardware, one RovState, one NavService, one estimator, the shipped
fill_nav_fields — or the two halves of this effort are describing two different
submarines and the seam between them is exactly where the last three bugs lived.

NO FIXTURE FILES. The dive log with the dead chips is FLOWN here, through the same
DiveLog the vehicle writes with, with MockHardware._kill_sensor stopping the part
mid-dive. A committed fixture is a file somebody regenerates to make a failing test
pass, and regenerating it IS lowering the bar.

stdlib unittest only, matching the rest of api/tests — see run.py for why there is no
framework here.
"""
from __future__ import annotations

import asyncio
import io
import itertools
import json
import logging
import os
import shutil
import tempfile
import types
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from typing import Union, get_args, get_origin

# ---------------------------------------------------------------------------
# Isolation, BEFORE anything reads the environment
# ---------------------------------------------------------------------------
# This module boots the REAL app (see CleanBootTest), and a real boot writes: a
# blackbox session journal, and — through NavService._recover_orphans — a rebuilt
# .geojson for any dive journal that never got a clean stop. Dive records are the one
# thing this project produces that cannot be regenerated by re-running anything, so a
# unit suite is not allowed anywhere near the real data/ directory. Everything lands
# in a temp tree that goes away with the process.
#
# Set here rather than in setUpClass because both settings objects are frozen
# dataclasses built at IMPORT time, and this module is imported before it is run.
_TMP = Path(tempfile.mkdtemp(prefix="neptune-consumers-"))
os.environ["NAV_DATA_DIR"] = str(_TMP)
os.environ["NAV_DIVES_DIR"] = str(_TMP / "dives")
os.environ["NAV_AREAS_DIR"] = str(_TMP / "areas")
os.environ["NAV_LUT_DIR"] = str(_TMP / "speed_luts")
os.environ["ROV_LOG_DIR"] = str(_TMP / "log")
# The WOLFANG camera is genuinely not on this bench's network, and the boot waits for
# its probe to time out. Shortening the wait changes how long the test takes and
# nothing about what is logged — the camera is absent either way, and CleanBootTest
# proves that from the boot's own report rather than assuming it.
os.environ.setdefault("WOLFANG_T_FAST", "0.25")
os.environ.setdefault("WOLFANG_T_SLOW", "0.25")

from config import settings                                          # noqa: E402
from nav import calibrate, cli                                       # noqa: E402
from nav.config import settings as nav_settings                      # noqa: E402
from nav.divelog import DiveLog                                      # noqa: E402
from nav.models import Origin                                        # noqa: E402
from nav.service import _feature_from_journal, build_router          # noqa: E402
from protocol import Telemetry                                       # noqa: E402
from tests.test_liveness import EVERYTHING, Chain                    # noqa: E402

# Belt and braces on the isolation above. nav.config caches its settings at import,
# and if any module in this process got there first the environment arrived too late —
# in which case the boot test would write into the operator's real dive directory. A
# frozen dataclass is frozen against accident, not against a test that says why.
for _attr, _sub in (("data_dir", ""), ("dives_dir", "dives"),
                    ("areas_dir", "areas"), ("speed_lut_dir", "speed_luts")):
    _want = _TMP / _sub if _sub else _TMP
    if Path(getattr(nav_settings, _attr)) != _want:
        object.__setattr__(nav_settings, _attr, _want)


# Quiet, deliberately — and put back afterwards.
#
# Every fixture here kills a chip, and killing one logs a WARNING, so without this the
# suite prints a page of alarms that are the fixture working correctly. Same technique
# and same reason as tests/test_liveness.py: the level goes on "neptune" alone (its
# children carry none of their own, so they inherit it) and is restored, because a test
# module that permanently silences the vehicle's logger is a worse bug than the noise.
#
# CleanBootTest is the exception and manages this itself: the whole point of that class
# is what the boot says out loud, so it re-opens the logger for its own duration.
_SAVED_LOG_LEVEL: int | None = None


def setUpModule() -> None:
    global _SAVED_LOG_LEVEL
    lg = logging.getLogger("neptune")
    _SAVED_LOG_LEVEL = lg.level
    lg.setLevel(logging.CRITICAL)


def tearDownModule() -> None:
    if _SAVED_LOG_LEVEL is not None:
        logging.getLogger("neptune").setLevel(_SAVED_LOG_LEVEL)
    shutil.rmtree(_TMP, ignore_errors=True)


ORIGIN = Origin(lat=52.0, lon=-1.0, accuracy=3.0, source="manual")

# How long the flown fixtures run, in SIMULATED seconds. MockHardware's clock is
# simulated, so this costs microseconds and no test ever sleeps on a wall clock. Long
# enough that the depth and the bearing have both moved a long way from where they
# were when the chip died — a frozen reading and an honest one are only
# distinguishable once the world underneath has moved on.
LEG_S = 8.0


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------
def fly_a_dive_with_dying_chips(directory: Path, dive_id: str = "dive-consumers") -> Path:
    """One dive journal: healthy first half, MS5837 and BNO085 dead for the second.

    Flown through the SHIPPED writer — NavService._tick calls DiveLog.add(ns, s) with
    the real NavState and the real SensorSample — so the file this produces is byte-
    for-byte the shape a canal dive produces. Both chips, because depth and heading are
    the two channels every reader below reaches for and they die independently on a
    real hull.
    """
    c = Chain()
    # Homed first: an un-homed syringe is legitimately null all the way through, and a
    # journal where `ballast` is null everywhere would make calibrate refuse for a
    # reason that has nothing to do with the chips this fixture is about.
    c.hw.ballast_home()
    c.svc.dive = DiveLog(dive_id, "2026-01-01T00:00:00Z", ORIGIN, directory=directory)
    c.arm(throttle=0.6, steer=0.4)
    c.fly(LEG_S)
    # Ballast settles at a depth, which is what depth_model needs to see before the
    # sensor is taken away from it.
    c.ballast("fill").fly(LEG_S)
    c.kill("ms5837", "bno085")
    c.fly(LEG_S)
    c.ballast("empty").fly(LEG_S)
    # save() writes the derived GeoJSON beside the journal and closes it, exactly as
    # NavService.stop_dive() ends a real dive — so the tests below read the two real
    # artifacts a finished dive leaves behind rather than reaching into the writer.
    c.svc.dive.save(directory)
    if c.tick_errors:
        raise AssertionError(
            "the dive journal could not even be WRITTEN once the chips stopped:\n  "
            + "\n  ".join(c.tick_errors))
    return directory / f"{dive_id}.jsonl"


def rows_of(path: Path) -> list[dict]:
    """The sample records in a journal, exactly as calibrate.read_dive would see them."""
    return [json.loads(ln) for ln in path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and json.loads(ln).get("type") == "s"]


def origin_endpoint(svc):
    """The SHIPPED POST /api/origin handler, out of the router main.py mounts.

    Called directly rather than over HTTP on purpose: the defect lives in the handler
    BODY (an unguarded round() on a bearing that may not exist), FastAPI turns whatever
    it raises into an opaque 500, and a test that reports "500" instead of the
    TypeError sends the next reader to the wrong file.
    """
    for route in build_router(svc).routes:
        if getattr(route, "path", None) == "/api/origin" and "POST" in getattr(route, "methods", ()):
            return route.endpoint
    raise AssertionError(
        "nav/service.py no longer exposes POST /api/origin — capturing the launch point "
        "has moved, and this suite must follow it there rather than quietly stop "
        "checking the call that has to succeed before any dive can be logged.")


# ---------------------------------------------------------------------------
# POST /api/origin — the launch point, captured on a hull with no compass
# ---------------------------------------------------------------------------
class OriginTest(unittest.TestCase):
    """heading0 (§4.4) is read off the sub's IMU at the instant the origin is set, and
    the IMU is a chip that can be dead by then — the operator is standing on the bank
    with the sub in the water, which is precisely when a connector that vibrated loose
    in the van makes itself known.

    Two things have to hold and only one of them is the crash. The call must succeed;
    and what it stores must be an ADMISSION rather than a bearing. 0.0 is due north,
    and this number is the datum the whole track's rotation is expressed against — a
    fabricated north here tilts every dive logged from this origin, permanently, in a
    file that outlives the dive by years.
    """

    def setUp(self):
        self.c = Chain()
        self.c.arm(throttle=0.5, steer=0.3).fly(2.0)

    def test_a_live_compass_is_still_stamped_onto_the_origin(self):
        # The inverse first: a fix that answered "no bearing" always would satisfy every
        # assertion below and destroy the feature.
        bearing = self.c.svc.last_sample.heading_deg
        self.assertIsNotNone(bearing, "the fixture must have a compass before it kills one")
        res = asyncio.run(origin_endpoint(self.c.svc)(
            Origin(lat=52.0, lon=-1.0, accuracy=3.0, source="manual"), False))
        self.assertTrue(res["ok"])
        self.assertAlmostEqual(self.c.svc.origin.heading_deg, round(bearing, 1), places=1,
                               msg="heading0 must be the IMU's own yaw at capture (§4.4)")

    def test_the_origin_can_be_captured_with_no_compass_answering(self):
        self.c.kill("bno085").fly(1.0)
        self.assertIsNone(self.c.svc.last_sample.heading_deg)
        try:
            res = asyncio.run(origin_endpoint(self.c.svc)(
                Origin(lat=52.0, lon=-1.0, accuracy=3.0, source="manual"), False))
        except Exception as exc:  # noqa: BLE001 — the regression this test exists for
            self.fail(f"POST /api/origin raised {type(exc).__name__}: {exc} — a dead "
                      f"BNO085 must not stop the operator setting a launch point. "
                      f"Capturing the origin is what starts the dive log, so this is a "
                      f"500 on the one call that has to work before anything can be "
                      f"recorded at all.")
        self.assertTrue(res["ok"])

    def test_the_origin_records_that_it_had_no_bearing(self):
        self.c.kill("bno085").fly(1.0)
        asyncio.run(origin_endpoint(self.c.svc)(
            Origin(lat=52.0, lon=-1.0, accuracy=3.0, source="manual"), False))
        for where, value in (("the stored origin", self.c.svc.origin.heading_deg),
                             ("the response body", self.c.svc.origin.model_dump()["heading_deg"])):
            if value == 0.0 and value is not None:
                self.fail(f"{where}: heading_deg=0.0 with no IMU answering. That is not a "
                          f"blank, it is DUE NORTH — and heading0 is the datum every track "
                          f"logged from this origin is rotated against, so it is a "
                          f"fabricated bearing baked permanently into the record.")
            self.assertIsNone(value, f"{where}: heading_deg={value!r}, expected null")

    def test_a_bearingless_origin_survives_the_dive_journal_and_comes_back(self):
        # divelog.py writes origin.model_dump() into the journal header and
        # cli.load_replay_log rebuilds it with Origin(**header["origin"]). If the model
        # cannot hold the null, the null cannot be written; if it cannot be read back,
        # every replay of a dive launched without a compass refuses to load.
        self.c.kill("bno085").fly(1.0)
        asyncio.run(origin_endpoint(self.c.svc)(
            Origin(lat=52.0, lon=-1.0, accuracy=3.0, source="manual"), False))
        d = Path(_TMP / "origin-null")
        log = DiveLog("dive-noheading", "2026-01-01T00:00:00Z", self.c.svc.origin, directory=d)
        geojson = log.save(d)
        header = json.loads((d / "dive-noheading.jsonl").read_text(encoding="utf-8").splitlines()[0])
        self.assertIn("heading_deg", header["origin"],
                      "the key was dropped rather than nulled — a reader cannot tell an "
                      "old journal from one launched with no compass")
        self.assertIsNone(header["origin"]["heading_deg"])
        rebuilt = Origin(**header["origin"])
        self.assertIsNone(rebuilt.heading_deg,
                          "the journal header round-trips the null or no dive launched "
                          "without a compass can ever be replayed (cli.load_replay_log "
                          "rebuilds the origin with exactly this call)")
        # And the GeoJSON's own reader. DiveLog.load() does `o.get("heading_deg", 0)`,
        # which is the present-and-null trap again: the default cannot fire on a key that
        # is there, so the None goes into the model and either survives or raises.
        self.assertIsNone(DiveLog.load(geojson).origin.heading_deg)


# ---------------------------------------------------------------------------
# The dive log's readers — present-and-null is not a missing key
# ---------------------------------------------------------------------------
class JournalReadersTest(unittest.TestCase):
    """The permanent record, read by the three things that read it.

    A dive journal is the only artifact of a dive that cannot be regenerated, and it is
    the one file whose entire purpose is to be read back — by `nav.cli replay` (score
    the estimators), by `nav.cli calibrate` (derive the model constants) and by
    NavService._recover_orphans (rebuild a dive the power cut interrupted). All three
    were written against a log in which every column is a number.
    """

    @classmethod
    def setUpClass(cls):
        cls.dir = _TMP / "journal"
        cls.path = fly_a_dive_with_dying_chips(cls.dir)
        cls.rows = rows_of(cls.path)

    # ---- the fixture's own claim, before anything is built on it ----------
    def test_the_journal_carries_the_columns_PRESENT_AND_NULL(self):
        self.assertGreater(len(self.rows), 100)
        for key in ("depth_m", "heading_deg", "raw_heading_deg", "psi", "mag_cal"):
            with self.subTest(column=key):
                present = [r for r in self.rows if key in r]
                self.assertEqual(len(present), len(self.rows),
                                 f"{key} is MISSING from some rows. A dead chip must null "
                                 f"its column, never drop it: a missing key and a null are "
                                 f"different claims and this whole suite turns on the "
                                 f"difference.")
                self.assertTrue(any(r[key] is None for r in present),
                                f"{key} is never null — the kill did not reach the journal, "
                                f"so nothing below is exercising anything")
                self.assertTrue(any(r[key] is not None for r in present),
                                f"{key} is null for the WHOLE log; a reader that refuses "
                                f"outright would pass every test here for the wrong reason")

    def test_read_dive_hands_the_null_on_rather_than_defaulting_it(self):
        _header, samples = calibrate.read_dive(self.path)
        dead = [s for s in samples if s.get("depth_m") is None]
        self.assertTrue(dead, "read_dive lost the nulls between the file and the caller")
        self.assertIn("depth_m", dead[0])
        self.assertIsNone(dead[0]["depth_m"])
        self.assertIsNone(dead[0]["heading_deg"])

    # ---- nav.cli replay ---------------------------------------------------
    def test_replay_loads_a_dive_whose_chips_died(self):
        log = cli.load_replay_log(self.path)
        self.assertGreater(len(log.samples), 100)
        self.assertTrue(any(s.depth_m is None for s in log.samples),
                        "the reader coerced a null depth back into a number on the way "
                        "into the estimator — 0.0 m is AT THE SURFACE, which is the one "
                        "depth a sub holding ballast is not at")
        self.assertTrue(any(s.heading_deg is None for s in log.samples),
                        "the reader coerced a null bearing back into a number — 0.0 is "
                        "due north, and the dead reckoner runs the track along it")

    def test_replay_runs_end_to_end_and_scores_it(self):
        out = io.StringIO()
        try:
            with redirect_stdout(out):
                rc = cli.main(["replay", str(self.path), "--filter", "both"])
        except Exception as exc:  # noqa: BLE001 — the regression this test exists for
            self.fail(f"`nav.cli replay` raised {type(exc).__name__}: {exc} on a dive "
                      f"whose sensors stopped. That is the dive most worth replaying, and "
                      f"it is the only one the tool cannot read.\n{out.getvalue()[-1200:]}")
        self.assertEqual(rc, 0, out.getvalue()[-1200:])
        for expected in ("--- dr ---", "--- filtered ---"):
            self.assertIn(expected, out.getvalue())

    def test_the_score_carries_the_null_instead_of_a_final_depth_of_zero(self):
        log = cli.load_replay_log(self.path)
        sc = cli.score(cli.replay(log, "dr"), log)
        self.assertIsNone(sc["final_depth"],
                          f"final_depth={sc['final_depth']!r} for a dive that ended with "
                          f"the MS5837 dead. A replay summary that prints 0.0 m says the "
                          f"sub finished at the surface, which is a conclusion nothing "
                          f"measured.")

    # ---- nav.cli calibrate ------------------------------------------------
    def test_calibrate_runs_end_to_end_on_the_same_log(self):
        out = io.StringIO()
        try:
            with redirect_stdout(out):
                rc = cli.main(["calibrate", str(self.path)])
        except Exception as exc:  # noqa: BLE001 — the regression this test exists for
            self.fail(f"`nav.cli calibrate` raised {type(exc).__name__}: {exc}. The "
                      f"journal writes a dead chip as the key PRESENT AND NULL, and "
                      f"`.get(key, 0.0)` only fires on a MISSING key — so the default "
                      f"never fired and the None went straight into the arithmetic."
                      f"\n{out.getvalue()[-1200:]}")
        self.assertIn(rc, (0, 1), out.getvalue()[-1200:])

    def test_calibrate_selftest_still_passes(self):
        # The maths it derives is checked against a dive with KNOWN constants. Kept here
        # because everything above only proves calibrate does not crash, and a version
        # that swallowed the null and carried on with 0.0 would also not crash.
        out = io.StringIO()
        with redirect_stdout(out):
            rc = cli.main(["calibrate", "--selftest"])
        self.assertEqual(rc, 0, out.getvalue())

    # ---- the orphan rebuilder ---------------------------------------------
    def test_the_orphan_recovery_reader_keeps_the_nulls(self):
        # A journal with no .geojson beside it is a dive the process died in the middle
        # of — the dive most worth keeping. It is rebuilt on the next start, and the
        # rebuild must not fill the gaps in.
        feat = _feature_from_journal(self.path)
        self.assertIsNotNone(feat, "an unfinished dive rebuilt into nothing")
        blanks = [s for s in feat["samples"] if s["depth_m"] is None]
        self.assertTrue(blanks, "the recovered dive has a depth for every sample, "
                                "including the stretch nothing was measuring it")
        self.assertIsNone(blanks[-1]["heading_deg"])

    def test_the_saved_geojson_keeps_the_nulls(self):
        # The derived artifact — the one somebody opens in a map viewer a year later,
        # by which time it is all that is left of the dive.
        feat = json.loads(self.path.with_suffix(".geojson").read_text(encoding="utf-8"))
        self.assertTrue(any(s["depth_m"] is None for s in feat["samples"]),
                        "the GeoJSON filled in a depth nobody measured; a bathymetry "
                        "raster built from it has a hole punched through it at the surface")
        self.assertTrue(any(s["heading_deg"] is None for s in feat["samples"]))
        self.assertTrue(any(s.get("no_heading") for s in feat["samples"]),
                        "a run of identical coordinates with nothing marking it reads as "
                        "a sub sitting still, when what happened is that the compass "
                        "stopped and the track was held")


# ---------------------------------------------------------------------------
# PRESENT-AND-NULL vs MISSING — the distinction that broke calibrate.py
# ---------------------------------------------------------------------------
def synthetic_rows(n: int = 60, dt: float = 0.1, **overrides) -> list[dict]:
    """A steady armed steer-and-ballast segment, long enough for calibrate to use it.

    Hand-rolled rather than borrowed from calibrate's own _synthetic(): a test that
    builds its input with the private helper of the module under test stops being able
    to say anything when that helper changes shape.
    """
    rows = []
    for i in range(n):
        row = {"type": "s", "t": round((i + 1) * dt, 3), "x": 0.0, "y": 0.0,
               "depth_m": 4.0, "heading_deg": round((i * 4.0) % 360, 3),
               "snapped": False, "confidence": 1.0,
               "throttle": 0.5, "steer": 1.0, "left": 0.5, "right": 0.5,
               "ballast": 1.0, "ballast_tgt": 1.0, "psi": 20.4, "armed": True,
               "mag_cal": 3, "encoder_m": round(i * 0.05, 3)}
        row.update(overrides)
        rows.append(row)
    return rows


class PresentAndNullTest(unittest.TestCase):
    """`.get(key, default)` fires on a MISSING key and never on a null one.

    That sentence is the entire bug. divelog.py's docstring says a null is logged as
    null — "never 0.0, never the last value, never a key quietly dropped" — so every
    reader written with a `.get` default is defended against the one case that does not
    happen and undefended against the one that does. Both shapes are tested here
    together, because a reader that handles one and not the other looks correct in
    every review.
    """

    def test_the_control_case_actually_measures_something(self):
        # Without this the two refusals below would pass on a fixture calibrate cannot
        # read at all, which is the cheapest possible way for this class to be green.
        tr, why = calibrate.turn_rate(synthetic_rows())
        self.assertIsNotNone(tr, f"the fixture is not measurable at all: {why}")
        self.assertGreater(tr["deg_per_s_per_unit_steer"], 0.0)

    def test_a_column_that_is_present_and_null_is_tolerated(self):
        rows = synthetic_rows(heading_deg=None)
        self.assertIn("heading_deg", rows[0])
        try:
            tr, why = calibrate.turn_rate(rows)
        except Exception as exc:  # noqa: BLE001 — THE regression
            self.fail(f"turn_rate raised {type(exc).__name__}: {exc} on a column that is "
                      f"PRESENT AND NULL. That is what a dive journal looks like after a "
                      f"chip stops answering, and it is the shape every `.get(key, 0.0)` "
                      f"in a reader is blind to.")
        self.assertIsNone(tr, "a turn rate was derived from headings nobody measured")
        self.assertTrue(why, "it refused without saying why")

    def test_a_column_that_is_missing_entirely_is_tolerated_too(self):
        rows = [{k: v for k, v in r.items() if k != "heading_deg"} for r in synthetic_rows()]
        self.assertNotIn("heading_deg", rows[0])
        try:
            tr, why = calibrate.turn_rate(rows)
        except Exception as exc:  # noqa: BLE001
            self.fail(f"turn_rate raised {type(exc).__name__}: {exc} on a log that predates "
                      f"the heading column altogether")
        self.assertIsNone(tr)
        self.assertTrue(why)

    def test_the_depth_model_refuses_rather_than_fitting_a_surface(self):
        rows = synthetic_rows(depth_m=None)
        try:
            dm, why = calibrate.depth_model(rows)
        except Exception as exc:  # noqa: BLE001
            self.fail(f"depth_model raised {type(exc).__name__}: {exc} on a present-and-null "
                      f"depth column")
        self.assertIsNone(dm, "a ballast->depth constant was fitted to depths nobody took. "
                              "0.0 m is AT THE SURFACE, so a filled null does not weaken "
                              "the fit, it moves it — and quietly.")
        self.assertTrue(why)

    def test_the_replay_reader_makes_the_same_distinction(self):
        # cli._sample_from_row rebuilds a SensorSample from one journal line. It is the
        # only reader that has to be right about BOTH shapes at once, because it feeds
        # the estimators whose whole contract is that a null is not a reading.
        null_row = synthetic_rows(1)[0] | {"depth_m": None, "raw_heading_deg": None,
                                           "heading_deg": None, "psi": None, "mag_cal": None,
                                           "gyro_z_dps": None, "accel_fwd_ms2": None}
        s = cli._sample_from_row(null_row)
        for field in ("depth_m", "heading_deg", "pressure_psi", "mag_cal",
                      "gyro_z_dps", "accel_fwd_ms2"):
            with self.subTest(field=field):
                self.assertIsNone(getattr(s, field),
                                  f"{field} came back as {getattr(s, field)!r} from a "
                                  f"present-and-null column — the estimator is now being "
                                  f"fed a measurement that was never taken")
        missing_row = {k: v for k, v in synthetic_rows(1)[0].items()
                       if k not in ("depth_m", "heading_deg", "psi", "mag_cal")}
        s2 = cli._sample_from_row(missing_row)      # must not raise
        self.assertIsNotNone(s2)


# ---------------------------------------------------------------------------
# /ws/nav and /ws/control describe the same vehicle
# ---------------------------------------------------------------------------
# The same fact, under the name each socket gives it. ONE console is attached to both
# — the HUD reads telemetry, the map reads the nav frame — and they land in the same
# state slots on the client (client/js/map.js: "they are the same facts about the same
# vehicle"). A fact that is null on one socket and a confident value on the other is
# not two opinions, it is whichever frame arrived last, and the operator cannot tell
# which they are looking at.
_SHARED_FACTS = (
    ("heading", "heading_deg"),
    ("depth", "depth_m"),
    ("mag_cal", "mag_cal"),
    ("snagged", "snagged"),
    ("gyro_only", "gyro_only"),
    ("speed_ms", "speed_ms"),
    ("speed_src", "speed_src"),
)


class TwoSocketsOneVehicleTest(unittest.TestCase):
    """gyro_only was null on /ws/control and false on /ws/nav in the SAME TICK.

    Not a cosmetic mismatch. false is navigation's REASSURING answer — "the filter
    looked, and it is using the compass" — and null is "navigation cannot say". The
    client keys its RAW COMPASS badge on exactly that distinction (client/js/core.js
    headingFlag: `state.gyroOnly == null && state.navAnswered`), so a nav frame
    carrying false silently re-arms the trust mark that the telemetry frame beside it
    had just withdrawn. Whichever socket ticked last wins, and neither is wrong on its
    own terms.
    """

    def _frames(self, chain: Chain):
        """The two frames as the two sockets would send them, from ONE tick."""
        tel = chain.frame()
        ns = chain.svc.fresh_state()
        return tel, (None if ns is None else chain.svc.nav_frame(ns))

    def assertAgree(self, tel, nav, note: str) -> None:
        if nav is None:
            # Navigation is not answering, so /ws/nav sends NOTHING (service.py declines
            # the catch-up push and the broadcast never happens). Silence cannot
            # contradict a null, and fill_nav_fields has already blanked the fields it
            # owns. That IS agreement.
            self.assertIsNone(tel.snagged)
            self.assertIsNone(tel.gyro_only)
            return
        bad = []
        for tel_key, nav_key in _SHARED_FACTS:
            t, n = getattr(tel, tel_key), nav.get(nav_key)
            if (t is None) != (n is None):
                bad.append(f"{tel_key}: /ws/control says {t!r}, /ws/nav says "
                           f"{nav_key}={n!r} — one of them is a claim and the other is "
                           f"an admission, about the same vehicle in the same tick")
        self.assertEqual(bad, [], "\n".join(
            [f"the two sockets disagree about what is known ({note}):"] + bad))

    def test_a_healthy_hull_is_complete_on_both_sockets(self):
        c = Chain()
        c.hw.ballast_home()
        c.arm(throttle=1.0).fly(2.0)
        tel, nav = self._frames(c)
        self.assertIsNotNone(nav, "navigation must be answering, or this proves nothing")
        for tel_key, nav_key in _SHARED_FACTS:
            self.assertIsNotNone(getattr(tel, tel_key), f"telemetry {tel_key} is null on a "
                                                        f"vehicle whose sensors all answer")
            self.assertIsNotNone(nav[nav_key], f"the nav frame's {nav_key} is null on a "
                                               f"vehicle whose sensors all answer")
        self.assertAgree(tel, nav, "everything answering")

    def test_a_dead_compass_blanks_the_bearing_on_BOTH_sockets(self):
        c = Chain().arm(throttle=1.0, steer=0.5).fly(2.0)
        c.kill("bno085").fly(2.0)
        tel, nav = self._frames(c)
        self.assertIsNone(tel.heading)
        self.assertAgree(tel, nav, "bno085 dead")

    def test_gyro_only_is_null_on_both_or_on_neither(self):
        # The headline. fill_nav_fields nulls gyro_only whenever the frame carries no
        # bearing ("it qualifies a heading, so it cannot outlive one"); the nav frame is
        # dumped straight off NavState and has to reach the same verdict.
        c = Chain().arm(throttle=1.0, steer=0.5).fly(2.0)
        c.kill("bno085").fly(2.0)
        tel, nav = self._frames(c)
        if nav is not None:
            self.assertEqual(
                tel.gyro_only is None, nav["gyro_only"] is None,
                f"/ws/control gyro_only={tel.gyro_only!r} but /ws/nav gyro_only="
                f"{nav['gyro_only']!r} with no bearing on either. false is navigation's "
                f"REASSURING answer, and the console's RAW COMPASS badge is keyed on "
                f"telling that apart from 'cannot say'.")

    def test_every_combination_of_dead_parts_agrees(self):
        # The combinations are where this breaks: each socket's fields were filled in by
        # a different `if` written against one failure at a time.
        for n in range(len(EVERYTHING) + 1):
            for dead in itertools.combinations(EVERYTHING, n):
                with self.subTest(dead=dead):
                    c = Chain().arm(throttle=0.6, steer=0.3).fly(1.0)
                    c.stop(*dead).fly(1.0)
                    tel, nav = self._frames(c)
                    self.assertAgree(tel, nav, f"dead={list(dead)}")
                    self.assertEqual(c.tick_errors, [], "\n".join(c.tick_errors))


# ---------------------------------------------------------------------------
# protocol.Telemetry — the contract, exercised as a contract
# ---------------------------------------------------------------------------
# Every field a healthy frame must still supply, filled here with its CANNOT-TELL
# value where it has one: this is a frame from a vehicle where nothing is answering,
# which is the frame the whole round is about. leak=True is "not certified dry",
# leak_state UNKNOWN is the probes not being sampled, signal -1 is no link reading.
# None of these three has a null to spend — their cannot-tell is spelled out instead —
# and that is exactly why they are easy to forget.
_REQUIRED_TELEMETRY = {
    "armed": False, "left": 0.0, "right": 0.0, "ballast_target": 0.0,
    "magnet": False, "light_green": False, "light_white": False,
    "light_green_level": 0.0, "light_white_level": 0.0,
    "leak": True, "leak_state": "UNKNOWN", "signal": -1, "mock": True,
}

# The readings a SENSOR stands behind. Each one can stop mid-dive, so each one must
# have a null to spend — a required float leaves a dead sensor nowhere to say so, and
# that is the hole three consecutive rounds fell into, in a different file each time.
_MUST_BE_NULLABLE = ("depth", "pressure", "heading", "heading_card", "mag_cal",
                     "battery_v", "current_a", "ballast_level", "speed_ms", "speed_src",
                     "snagged", "gyro_only", "leak_probe_fault", "link_ms")


def optional_telemetry_fields() -> list[str]:
    """Every Telemetry field whose declared type admits None, read off the model."""
    out = []
    for name, field in Telemetry.model_fields.items():
        origin = get_origin(field.annotation)
        if origin in (Union, types.UnionType) and type(None) in get_args(field.annotation):
            out.append(name)
    return out


class TelemetryContractTest(unittest.TestCase):
    """A field is only Optional if a null SURVIVES THE WIRE, in both directions.

    The producer already violated this contract once: main.py was assigning None to
    snagged and gyro_only while protocol.py still declared them plain bools, so the
    server was emitting frames its own contract rejects (Telemetry.model_validate_json
    on a live frame: 2 validation errors). A contract the producer ignores is worse
    than no contract, because every consumer that trusts it is trusting a document
    nobody enforces. So it is enforced here, against the model itself, field by field
    and without a list of names to keep up to date.
    """

    def test_every_reading_that_can_stop_has_a_null_to_spend(self):
        optional = set(optional_telemetry_fields())
        missing = [f for f in _MUST_BE_NULLABLE if f not in optional]
        self.assertEqual(missing, [], f"{missing} cannot be null on the wire. Each of "
                                      f"these is measured by a part that can stop "
                                      f"answering mid-dive, and a required field leaves "
                                      f"the vehicle no way to say so — which is how a "
                                      f"frozen 4.33 m and a 0.0 V pack reached an "
                                      f"operator wearing full confidence.")

    def test_no_new_required_field_has_appeared_unexamined(self):
        required = {n for n, f in Telemetry.model_fields.items() if f.is_required()}
        self.assertEqual(required, set(_REQUIRED_TELEMETRY), msg=(
            "the set of REQUIRED Telemetry fields has changed. This is not busywork: "
            "the question a new required field has to answer is 'can the thing behind "
            "it stop answering?', and if it can, a required field gives it nowhere to "
            "say so. If the new field is a reading, make it Optional and add it to "
            "_MUST_BE_NULLABLE; if it genuinely cannot be absent, add it here with the "
            "value a vehicle in trouble would send."))

    def test_every_optional_field_round_trips_as_null(self):
        optional = optional_telemetry_fields()
        self.assertGreater(len(optional), 20, "the model lost most of its nullable fields")
        tel = Telemetry(**_REQUIRED_TELEMETRY, **{name: None for name in optional})
        raw = tel.model_dump_json()
        on_wire = json.loads(raw)
        back = Telemetry.model_validate_json(raw)
        for name in optional:
            with self.subTest(field=name):
                self.assertIn(name, on_wire,
                              f"{name} was dropped from the JSON entirely rather than sent "
                              f"as null. A consumer that asks whether the key is there "
                              f"then reads a dead sensor as an old vehicle that never had "
                              f"one — two different faults, one appearance.")
                self.assertIsNone(on_wire[name], f"{name} serialised as {on_wire[name]!r}")
                self.assertIsNone(getattr(back, name),
                                  f"{name} came back as {getattr(back, name)!r} after "
                                  f"model_validate_json — the null did not survive a "
                                  f"round trip through the contract that defines it")

    def test_a_frame_that_omits_them_still_validates(self):
        # The other direction: a vehicle older or newer than this contract must not have
        # its frames rejected outright. A dropped socket is a worse outcome than a
        # missing gauge, and the null on each reading is the primary evidence anyway.
        raw = json.dumps({"type": "telemetry", **_REQUIRED_TELEMETRY})
        tel = Telemetry.model_validate_json(raw)
        for name in _MUST_BE_NULLABLE:
            self.assertIsNone(getattr(tel, name),
                              f"{name} defaulted to {getattr(tel, name)!r} on a frame that "
                              f"never mentioned it — an absent field must land on "
                              f"cannot-tell, never on a plausible reading")

    def test_the_cannot_tells_that_are_not_nulls_survive_too(self):
        # leak_state and signal have no null to spend, so their cannot-tell is a value:
        # "UNKNOWN" and -1. A round trip that quietly normalised either one would undo
        # the only way those two readings have of admitting anything.
        tel = Telemetry.model_validate_json(
            Telemetry(**_REQUIRED_TELEMETRY).model_dump_json())
        self.assertEqual(tel.leak_state, "UNKNOWN")
        self.assertEqual(tel.signal, -1)
        self.assertIs(tel.leak, True, "the old single-bit alarm must not read as a dry hull")


# ---------------------------------------------------------------------------
# A clean boot says nothing alarming
# ---------------------------------------------------------------------------
BOOT_SETTLE_S = 1.0


class _Capture(logging.Handler):
    def __init__(self) -> None:
        super().__init__(level=logging.NOTSET)
        self.records: list[logging.LogRecord] = []

    def emit(self, record: logging.LogRecord) -> None:
        self.records.append(record)


class CleanBootTest(unittest.TestCase):
    """A WARNING that fires on every healthy start is a warning nobody reads.

    main.py's log_nav_change() says so in its own docstring and then did it anyway: the
    control loop is created BEFORE nav_svc.start() in the lifespan, so its first tick
    found loop_state() == "never-started", took that for a subsystem that had stopped,
    and printed "navigation has STOPPED answering for this hull — speed, snag and
    heading-trust go to cannot-tell" at WARNING on a vehicle where navigation was about
    to come up perfectly. The day that line means something it will look exactly like
    every other day.

    THE REAL BOOT, not a stand-in: `async with main.lifespan(main.app)` is precisely
    what uvicorn does, so this brings up the hardware layer, the control loop, the
    watchdog, the blackbox, the camera plane and navigation, in the shipped order.
    Everything it writes goes into the temp tree at the top of this file.

    WHICH WARNINGS ARE ALLOWED IS TAKEN FROM THE BOOT'S OWN ADMISSIONS rather than from
    a list kept here. This bench has no GPIO and no camera on its network, and saying
    so is TRUE — demanding silence about them would be demanding a lie. So the
    allowance is derived: `hw.is_mock` licenses neptune.hw to complain, `camera.kind ==
    "none"` licenses neptune.cam. Navigation is neither absent nor mocked, and has no
    licence at all.
    """

    @classmethod
    def setUpClass(cls):
        root = logging.getLogger()
        cls._saved_handlers, cls._saved_level = root.handlers[:], root.level
        cls._saved_neptune = logging.getLogger("neptune").level
        # Installed BEFORE main is imported, for two reasons: main.py calls
        # logging.basicConfig() at import, which is a no-op once the root logger already
        # has a handler (so the suite does not spray a page of INFO onto the runner's
        # stderr), and the very first records of the boot are the ones under test.
        cls.cap = _Capture()
        root.handlers = [cls.cap]
        root.setLevel(logging.INFO)
        logging.getLogger("neptune").setLevel(logging.NOTSET)

        import main                        # noqa: PLC0415 — deliberately late; see above

        async def _boot():
            async with main.lifespan(main.app):
                await asyncio.sleep(BOOT_SETTLE_S)
                cls.health = main.app.state.nav_svc.health()
                cls.hw_is_mock = bool(main.app.state.hw.is_mock)
                cls.camera_kind = str(main.app.state.camera.kind)

        asyncio.run(_boot())
        cls.records = list(cls.cap.records)

    @classmethod
    def tearDownClass(cls):
        root = logging.getLogger()
        root.handlers, root.level = cls._saved_handlers, cls._saved_level
        logging.getLogger("neptune").setLevel(cls._saved_neptune)

    def _warnings(self) -> list[logging.LogRecord]:
        return [r for r in self.records if r.levelno >= logging.WARNING]

    def _licensed_prefixes(self) -> tuple[str, ...]:
        out = []
        if self.hw_is_mock:
            out.append("neptune.hw")          # no GPIO on a bench: the fallback IS the news
        # "synthetic" belongs here for exactly the reason the other two do: SyntheticCamera
        # is the animated bench pattern, chosen by get_camera() only when there is NO real
        # camera to open. Its two warnings — picamera2 absent, and the WOLFANG CGI not
        # answering — are the console saying WHY you are looking at a test card, which is
        # news worth having once. Leaving it off this list failed every bench boot on the
        # dev machine, where NEPTUNE_CAM=auto plus an installed Pillow lands on synthetic:
        # a permanently red check, which is the same defect this test exists to prevent,
        # one level up. A warning that always fires gets read past; so does a test that
        # always fails.
        if self.camera_kind in ("none", "mock", "synthetic"):
            out.append("neptune.cam")         # no camera on this network, and it said so
        return tuple(out)

    def test_the_boot_actually_came_up(self):
        # Without this, everything below could pass on a boot that never happened.
        self.assertTrue(any(r.getMessage().startswith("NEPTUNE API up") for r in self.records),
                        "the lifespan never reached the line that says the api is up")
        self.assertTrue(any("control loop @" in r.getMessage() for r in self.records))

    def test_navigation_was_healthy_throughout(self):
        # The premise of the next test: if navigation really HAD stopped, warning about
        # it would be correct and demanding silence would be the bug.
        self.assertEqual(self.health["loop"], "running", self.health)
        self.assertEqual(self.health["tick_faults"], 0, self.health)
        self.assertIsNone(self.health["last_fault"], self.health)
        self.assertIsNone(self.health["loop_end_reason"], self.health)
        self.assertTrue(self.health["reads_vehicle"], self.health)

    def test_a_clean_healthy_boot_logs_no_warning(self):
        licensed = self._licensed_prefixes()
        bad = [r for r in self._warnings() if not r.name.startswith(licensed)]
        self.assertEqual(
            [], [f"{r.levelname} {r.name}: {r.getMessage()}" for r in bad],
            "a boot with nothing wrong with it warned anyway. A warning that fires every "
            "time is a warning that gets read past, and the day one of these means "
            "something it will be indistinguishable from today.\n"
            f"(licensed to complain, from the boot's own report: {list(licensed)} — "
            f"hw_is_mock={self.hw_is_mock}, camera={self.camera_kind!r})")

    def test_navigation_is_not_indicted_before_it_has_been_started(self):
        # Named separately from the sweep above because the failure has a specific shape
        # worth recognising on sight: the control loop is created before nav in the
        # lifespan, so nav's own "never-started" reads to it as a subsystem that died.
        said = [r.getMessage() for r in self.records
                if r.levelno >= logging.WARNING and "navigation" in r.getMessage().lower()]
        self.assertEqual(said, [], "navigation was reported as broken during a boot in "
                                   f"which it came up clean ({self.health}). "
                                   "'Not started yet' and 'stopped answering' are opposite "
                                   "facts about a subsystem and must not share a line.")


if __name__ == "__main__":
    unittest.main()
