"""Blackbox flight recorder — Pi side (spec §1).

Two JSONL files per session under the log dir, kept SEPARATE (client events arrive
late, batched, out of order; interleaving would corrupt the Pi log's ordering — we
merge at analysis time, never write time):

    navigation_<session>.jsonl   ← this process writes, one event per line
    client_<session>.jsonl       ← uploaded verbatim from the topside client (§5)
    current.jsonl -> navigation_<session>.jsonl   (convenience symlink)

Where the log dir is: $ROV_LOG_DIR if set, else /var/log/rov on the Pi, else
<repo>/data/log on a bench machine. See _resolve_log_dir, which had to be taught
that /var is not a place on Windows.

Session identity (§1): session_id is the UTC filename stamp; pi_boot_id is unique
per process so a client can detect a Pi reboot and start a fresh client file.

Timestamps are the Pi's own MONOTONIC clock in milliseconds (never wall-clock —
monotonic can't jump backwards). The client keeps its own monotonic time; the two
are reconciled in analysis using the logged clock_sync offsets, never rewritten.
"""
from __future__ import annotations

import json
import logging
import os
import threading
import time
import uuid
from pathlib import Path

log = logging.getLogger("neptune.blackbox")


# The vehicle's log directory. deploy/systemd/neptune-api.service hands this same
# path to the service as ROV_LOG_DIR and lets systemd's LogsDirectory= create and own
# it, so on the Pi the environment answers first and this constant is only the default
# for someone running the API by hand.
PI_LOG_DIR = "/var/log/rov"
# The bench's. Gitignored (`data/` in .gitignore), inside the checkout, next to the
# dive logs and offline areas — where somebody looking for what a session produced
# would actually look.
BENCH_LOG_DIR = Path(__file__).resolve().parents[2] / "data" / "log"


def _resolve_log_dir() -> Path:
    """Where the blackbox writes: $ROV_LOG_DIR, else the default for this platform.

    ROV_LOG_DIR IS ALWAYS TRIED FIRST and on every platform — the Pi's systemd unit
    sets it, and so does anyone pointing a session at a USB stick.

    The default used to be /var/log/rov everywhere, which is a POSIX path and only
    names a real place where POSIX does. On Windows it does not fail loudly, which is
    worse: Path("/var/log/rov") resolves against the CURRENT DRIVE, mkdir(parents=True)
    cheerfully creates C:\\var\\log\\rov, the writability probe passes, and every bench
    boot logged "blackbox recording -> \\var\\log\\rov\\navigation_<ts>.jsonl". Sessions
    piled up in a directory at the root of the system drive — outside the repo, out of
    reach of the gitignore that was written to cover them, and nowhere anyone would
    think to look. Dive records are the one thing this project produces that cannot be
    regenerated by re-running anything, so the default has to be a real directory on
    the machine actually running.
    """
    candidates = [os.environ.get("ROV_LOG_DIR")]
    if os.name == "posix":
        candidates.append(PI_LOG_DIR)
    candidates.append(str(BENCH_LOG_DIR))

    tried: list[str] = []
    for cand in candidates:
        if not cand:
            continue
        p = Path(cand)
        tried.append(str(p))
        try:
            p.mkdir(parents=True, exist_ok=True)
            testf = p / ".wtest"
            testf.write_text("x"); testf.unlink()
            return p.resolve()
        except Exception:  # noqa: BLE001 — not writable (not root, read-only fs)
            continue
    # Nowhere to write. Say which places were rejected rather than letting the last
    # mkdir's bare OSError stand in for it: "Permission denied: '/var/log/rov'" reads
    # like the only path that was ever considered.
    raise RuntimeError("blackbox has nowhere to record: none of "
                       + ", ".join(tried) + " is writable. Set ROV_LOG_DIR.")


class BlackBox:
    """Append-only event recorder. Thread/async-safe (a lock guards each write);
    every write flushes so an abrupt power loss keeps all-but-the-last line."""

    def __init__(self, log_dir: Path | None = None) -> None:
        # .resolve() so the line logged at the end of __init__ names a full path. The
        # Windows bug described above announced "\var\log\rov\navigation_....jsonl",
        # a string that reads like a relative path and is not — nobody who saw it
        # learned that the records were landing at the root of C:.
        self.log_dir = (Path(log_dir) if log_dir else _resolve_log_dir()).resolve()
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.session_id = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
        self.pi_boot_id = uuid.uuid4().hex
        self._t0_wall = time.time()
        self.nav_path = self.log_dir / f"navigation_{self.session_id}.jsonl"
        self._lock = threading.Lock()
        self._f = self.nav_path.open("a", encoding="utf-8")
        self._link_current()
        self.event("session_start", {
            "session_id": self.session_id, "pi_boot_id": self.pi_boot_id,
            "wall_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        })
        # ASCII arrow. The arrow that used to be here was U+2192, which the Windows
        # console cannot encode, so this line came out as "blackbox recording \u2192
        # C:\..." - the one line that says where a dive is being recorded, delivered
        # with an escape sequence in the middle of it. Nothing this file logs is
        # decoration; keep it to characters every console the ROV is flown from can
        # actually print.
        log.info("blackbox recording -> %s", self.nav_path)

    def _link_current(self) -> None:
        cur = self.log_dir / "current.jsonl"
        try:
            if cur.exists() or cur.is_symlink():
                cur.unlink()
            cur.symlink_to(self.nav_path.name)
        except Exception:  # noqa: BLE001 — symlinks may be unsupported; not fatal
            pass

    def now_ms(self) -> float:
        """The Pi's monotonic clock in ms — the timebase for every logged event."""
        return time.monotonic() * 1000.0

    def session_info(self) -> dict:
        return {"session_id": self.session_id, "pi_boot_id": self.pi_boot_id,
                "pi_t_mono": round(self.now_ms(), 3)}

    def event(self, e: str, d: dict | None = None, c_id: str | None = None,
              t: float | None = None) -> None:
        rec: dict = {"t": round(t if t is not None else self.now_ms(), 3), "e": e}
        if c_id:
            rec["c_id"] = c_id
        if d is not None:
            rec["d"] = d
        line = json.dumps(rec, separators=(",", ":"))
        with self._lock:
            self._f.write(line + "\n")
            self._f.flush()

    def client_append(self, session_id: str, records: list[dict]) -> int:
        """Append client-uploaded records VERBATIM to client_<session>.jsonl (§5).
        Keyed by the client's session_id so a reboot lands in a fresh file."""
        safe = "".join(c for c in (session_id or "") if c.isalnum() or c in "TZ-_") or self.session_id
        path = self.log_dir / f"client_{safe}.jsonl"
        n = 0
        with self._lock:
            with path.open("a", encoding="utf-8") as f:
                for r in records:
                    f.write(json.dumps(r, separators=(",", ":")) + "\n")
                    n += 1
                f.flush()
        return n

    def close(self) -> None:
        with self._lock:
            try:
                self._f.flush(); self._f.close()
            except Exception:  # noqa: BLE001
                pass
